#!/usr/bin/env python3
"""Build grenzgaenger-homeoffice-telearbeit-regeln in 4 languages via article_template.build().
DRAFT — do not publish before claim_check gate passes (data/claim-check/claims-grenzgaenger-homeoffice.json)
and before the Oct 9 (TJPG) + mid-Nov (Dividenden) slots are consumed (card t_324c6147)."""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from article_template import build

SLUG = "grenzgaenger-homeoffice-telearbeit-regeln"
TITLE = {
 "de": "Grenzgänger im Homeoffice: die neuen Telearbeit-Regeln für Deutschland, Frankreich und Italien",
 "en": "Cross-Border Commuters Working from Home: the New Telework Rules for Germany, France and Italy",
 "fr": "Télétravail des frontaliers : les nouvelles règles pour l'Allemagne, la France et l'Italie",
 "it": "Lavoro da casa per i frontalieri: le nuove regole del telelavoro per Germania, Francia e Italia",
}
META = {
 "de": "Homeoffice aus dem Wohnsitzland ist das Minenfeld für Grenzgänger: 40-%-Toleranz im Zusatzabkommen CH-FR, 60 Nichtrückkehrtage im DBA CH-DE, 49,9-%-Rahmen für die Sozialversicherung. Regeln, Fristen, Formulare 2026/2027.",
 "en": "Working from home in your country of residence is a minefield for cross-border commuters: the 40 % tolerance in the CH-FR supplementary convention, 60 non-return days in the CH-DE treaty, the 49.9 % social-security framework. Rules, deadlines, forms 2026/2027.",
 "fr": "Le télétravail depuis l'État de résidence est un champ de mines pour les frontaliers : tolérance de 40 % dans le protocole additionnel CH-FR, 60 jours de non-retour dans la convention CH-DE, cadre de 49,9 % pour les assurances sociales. Règles, délais, formulaires 2026/2027.",
 "it": "Il lavoro da casa nello Stato di domicilio è un campo minato per i frontalieri: tolleranza del 40 % nel protocollo addizionale CH-FR, 60 giorni di non ritorno nella convenzione CH-DE, quadro del 49,9 % per le assicurazioni sociali. Regole, termini, moduli 2026/2027.",
}
H2 = {
 "de": "Homeoffice über der Grenze: was 2026/2027 gilt",
 "en": "Working from home across the border: what applies in 2026/2027",
 "fr": "Télétravail transfrontalier : ce qui s'applique en 2026/2027",
 "it": "Telelavoro oltre confine: cosa vale nel 2026/2027",
}
RELATED = ["grenzgaenger-de-fr-it-steuern.html", "steuer-checkliste-2026.html", "steuern-sparen-tipps.html"]

DE = [
(H2["de"],
"""<p>Wer als Grenzgänger aus dem Homeoffice arbeitet, bewegt sich auf zwei getrennten rechtlichen Gleisen: dem <strong>Steuerrecht</strong> (wo darf dein Lohn besteuert werden?) und dem <strong>Sozialversicherungsrecht</strong> (in welchem Land bist du versichert?). Die meisten Fehler passieren, weil Regeln des einen Gleises auf das andere übertragen werden. Stand 2026/2027, jeweils gegen den Primärtext geprüft:</p>
<ul class="tick"><li><strong>Frankreich (Steuer):</strong> Drei Regime je nach Arbeitskanton — Vereinbarung von 1983 (acht Grenzkantone: Lohn nur in Frankreich steuerbar, CH erhält 4,5 % Ausgleich), Kanton Genf (volle Quellensteuer in CH, 3,5 %-Ausgleich an Ain/Haute-Savoie, Freigrenze 15 % bei Telearbeit), übrige Kantone (ordentliches DBA). Gemeinsam ist die <strong>40-Prozent-Telearbeit-Grenze</strong> pro Kalenderjahr (Zusatzabkommen in Kraft seit 24. Juli 2025).</li><li><strong>Deutschland (Steuer):</strong> Das DBA CH-DE kennt <strong>keine prozentuale Homeoffice-Toleranz</strong>. Es gilt das Tagesprinzip (Art. 15) plus die Grenze von <strong>60 Nichtrückkehrtagen</strong> (Art. 15a Abs. 2).</li><li><strong>Sozialversicherung (alle Nachbarländer):</strong> Die multilaterale Rahmenvereinbarung lässt bis zu <strong>49,9 Prozent Telearbeit</strong>, ohne dass die Versicherungspflicht kippt — aber nur mit <strong>Bescheinigung A1</strong>.</li></ul>"""),
("Frankreich: drei Regime — der Arbeitskanton entscheidet",
"""<p>Die steuerliche Zuteilung für Grenzgänger mit Wohnsitz in Frankreich hängt davon ab, wo der Arbeitgeber sitzt. Drei Regime, ein gemeinsamer Nenner: die Telearbeit-Grenze von 40 Prozent pro Kalenderjahr (rückwirkend für ab dem 1. Januar 2023 ausbezahlte Vergütungen, dauerhaft seit dem Inkrafttreten des Zusatzabkommens am 24. Juli 2025).</p>
<ul><li><strong>Kantone der Vereinbarung von 1983</strong> (BE, BL, BS, JU, NE, SO, VD, VS): Der Lohn ist ausschliesslich im Ansässigkeitsstaat Frankreich steuerbar; Frankreich überweist der Schweiz einen Ausgleich von 4,5 Prozent der Bruttolohnsumme. Telearbeit bis 40 Prozent pro Jahr ändert daran nichts; darüber hinaus geht der Grenzgängerstatus verloren.</li><li><strong>Kanton Genf</strong> (Abkommen vom 29. Januar 1973): Die Schweiz besteuert den Lohn vollständig an der Quelle; Genf entrichtet den Departementen Ain und Haute-Savoie jährlich 3,5 Prozent der Bruttolohnsumme. Für den Telearbeits-Ausgleich gilt eine <strong>Freigrenze von 15 Prozent</strong>: gezahlt wird nur für den Anteil zwischen 15 und 40 Prozent.</li><li><strong>Übrige Kantone</strong> (ordentliches DBA): Besteuert wird, wo die Arbeit physisch ausgeübt wird. Telearbeit aus Frankreich gilt bis zu <strong>40 Prozent der Arbeitszeit pro Kalenderjahr</strong> als beim Arbeitgeber in der Schweiz verrichtet (Zusatzprotokoll Ziff. 1 Bst. a); die Schweiz zahlt Frankreich 40 Prozent der auf die Telearbeit entfallenden Steuern als Ausgleich.</li></ul>
<p>In die 40 Prozent hinein zählen auch <strong>temporäre Einsätze</strong> (Geschäfts- und Dienstreisen) im Ansässigkeitsstaat oder in einem Drittstaat — allerdings nur bis zu einer <strong>Gesamtdauer von zehn Tagen pro Jahr</strong> (Ziff. 3). Wer über 40 Prozent hinauskommt, wird <strong>ab dem ersten Telearbeitstag</strong> nach Art. 17 Abs. 1–3 DBA aufgeteilt: Der Telearbeit-Anteil ist neu im Ansässigkeitsstaat steuerbar, und der Ausgleich entfällt (Ziff. 1 Bst. d). Das ist der teure Kippeffekt — er wirkt rückwirkend auf das ganze Jahr.</p>"""),
("Deutschland: kein Prozentrahmen, aber 60 Nichtrückkehrtage",
"""<p>Anders als oft gelesen: Das DBA CH-DE (SR 0.672.913.62) enthält <strong>keine Telearbeit-Bestimmung</strong>. Die viel zitierten Prozente stammen aus dem Sozialversicherungsrecht (siehe unten) — steuerlich gelten weiterhin:</p>
<ul><li><strong>Art. 15 (Tagesprinzip):</strong> Besteuert wird, wo die Arbeit physisch ausgeübt wird. Homeoffice-Tage in Deutschland liegen im Ansässigkeitsstaat und werden dort regulär mit dem Welteinkommen besteuert; die Schweiz besteuert die Arbeitstage auf ihrem Gebiet.</li><li><strong>Art. 15a (Grenzgängerprivileg):</strong> Die Schweiz erhebt auf dem Bruttolohn nur <strong>4,5 Prozent Quellensteuer</strong> (mit Ansässigkeitsbescheinigung Formular Gre-1). Dieser Tarif hängt nicht an der Zahl der Homeoffice-Tage, sondern an der <strong>regelmässigen Rückkehr</strong>: Verloren geht der Status erst bei <strong>mehr als 60 Arbeitstagen</strong> pro Kalenderjahr, an denen du aus beruflichen Gründen nicht nach Hause zurückkehrst (Geschäftsreisen mit Übernachtung, Pikettdienst).</li><li>Nach der Verständigungsvereinbarung liegt eine regelmässige Rückkehr vor, wenn du dich an <strong>mindestens 20 Prozent</strong> der vereinbarten Arbeitstage vom Wohnsitz an den Arbeitsort und zurück begibst.</li></ul>
<p>Reiner Homeoffice-Tarif: Wer von zu Hause in Deutschland aus arbeitet, kehrt damit per Definition an seinen Wohnsitz zurück — Homeoffice-Tage sind <strong>keine</strong> Nichtrückkehrtage. Schädlich sind nur die beruflich bedingten Übernachtungen im Tätigkeits- oder Drittstaat.</p>"""),
("Sozialversicherung: 25 / 49,9 Prozent — für DE, FR und IT gleich",
"""<p>Auf dem SV-Gleis gilt für alle Nachbarländer dasselbe Regime (Rahmenvereinbarung nach Art. 16 VO (EG) 883/2004, die die Schweiz seit dem 1. Juli 2023 anwendet, für Italien ab dem 1. Januar 2024):</p>
<ul><li><strong>Unter 25 Prozent</strong> Telearbeit im Wohnstaat: die Zuständigkeit bleibt nach den ordentlichen Regeln ohnehin bei der Schweiz.</li><li><strong>Zwischen 25 und 49,9 Prozent:</strong> Die Schweiz bleibt zuständig — aber nur, wenn der Arbeitgeber bei der AHV-Ausgleichskasse via die Plattform ALPS eine <strong>Bescheinigung A1</strong> beantragt (gültig bis 3 Jahre, verlängerbar). Ohne A1 bist du im Wohnstaat versicherungspflichtig.</li><li><strong>Über 50 Prozent:</strong> Zuständig wird der Wohnstaat.</li></ul>
<p>Wichtig: Die Rahmenvereinbarung betrifft <strong>nur die Sozialversicherung, nicht das Steuerrecht</strong>. Wer die 40-%-Steuer-Grenze mit Frankreich oder die 60-Tage-Grenze mit Deutschland überschreitet, bleibt SV-mässig unter 49,9 Prozent trotzdem in der Schweiz — und umgekehrt.</p>"""),
("Melde- und Bescheinigungspflichten seit 2025",
"""<ul><li><strong>Arbeitgeberbescheinigung (Art. 5a QStV):</strong> Seit dem 1. Januar 2025 muss der bisherige Arbeitgeber in Frankreich ansässigen Arbeitnehmenden bei einem <strong>unterjährigen Austritt auf Verlangen</strong> eine Bescheinigung über Telearbeitstage bzw. Telearbeitsquote, temporäre Einsätze im Ansässigkeits- und Drittstaat sowie Übernachtungen in der Schweiz ausstellen (ESTV-Formular). Nötig für den korrekten Übergang zum neuen Arbeitgeber.</li><li><strong>Automatischer Lohn Datenaustausch CH-FR:</strong> Die ESTV meldet Frankreich jährlich bis <strong>30. November</strong> des Folgejahres die Telearbeitstage/-quote und Bruttovergütungen der betroffenen Arbeitnehmer (Art. 28ter DBA CH-FR).</li></ul>"""),
("Konkret: Checkliste pro Lohnjahr",
"""<ol><li>Telearbeitstage und temporäre Einsätze <strong>pro Kalenderjahr zählen</strong> (Arbeitgeber in der Pflicht; eigene Aufzeichnung sicherheitshalber).</li><li>FR-Verhältnis: unter <strong>40 Prozent</strong> bleiben, Dritt-/Ansässigkeits-Einsätze unter <strong>10 Tagen</strong>.</li><li>DE-Verhältnis: berufliche <strong>Übernachtungen unter 60</strong> halten, Gre-1 jährlich erneuern.</li><li>SV: ab 25 Prozent Telearbeit <strong>A1 über den Arbeitgeber</strong> beantragen.</li><li>Bei Jobwechsel im Jahr: <strong>Bescheinigung nach Art. 5a QStV verlangen</strong>.</li></ol>
<p class="muted">Dies ist allgemeine Information, keine Rechts- oder Steuerberatung. Massgebend sind allein die Vertragstexte (fedlex AS 2025 486, SR 0.672.913.62) und die Weisungen von BSV und ESTV. Details hängen vom Tätigkeitskanton und vom Einzelfall ab — bei Grenzfällen früh abklären.</p>"""),
]

EN = [
(H2["en"],
"""<p>If you commute across the border and work from home, you are moving on two separate legal tracks: <strong>tax law</strong> (which country may tax your salary?) and <strong>social security law</strong> (which country are you insured in?). Most mistakes happen because rules from one track get applied to the other. State of play for 2026/2027, each point checked against the primary text:</p>
<ul class="tick"><li><strong>France (tax):</strong> Three regimes depending on the canton of work — the 1983 agreement (eight border cantons: salary taxable only in France, Switzerland receives a 4.5 % compensation), the canton of Geneva (full Swiss source taxation, 3.5 % payment to Ain/Haute-Savoie, a 15 % threshold for telework), and the remaining cantons (ordinary treaty). Shared across all: the <strong>40 % annual telework limit</strong> (supplementary convention in force since 24 July 2025).</li><li><strong>Germany (tax):</strong> The CH-DE treaty has <strong>no percentage telework tolerance</strong>. The day principle (Art. 15) plus the limit of <strong>60 non-return days</strong> (Art. 15a para. 2) apply.</li><li><strong>Social security (all neighbouring countries):</strong> The multilateral framework agreement allows up to <strong>49.9 % telework</strong> without switching your insurance — but only with an <strong>A1 certificate</strong>.</li></ul>"""),
("France: three regimes — the canton of work decides",
"""<p>For commuters resident in France, the tax allocation depends on where the employer sits. Three regimes, one common denominator: the 40 % annual telework limit (retroactive to remuneration paid from 1 January 2023, permanent since the supplementary convention entered into force on 24 July 2025).</p>
<ul><li><strong>Cantons of the 1983 agreement</strong> (BE, BL, BS, JU, NE, SO, VD, VS): the salary is taxable exclusively in France; France remits a 4.5 % compensation of the gross payroll to Switzerland. Telework up to 40 % changes nothing; beyond it the commuter status is lost.</li><li><strong>Canton of Geneva</strong> (agreement of 29 January 1973): Switzerland taxes the salary fully at source; Geneva pays the departments of Ain and Haute-Savoie 3.5 % of the gross payroll annually. For the telework compensation a <strong>15 % threshold</strong> applies: payment is due only on the share between 15 and 40 %.</li><li><strong>Remaining cantons</strong> (ordinary treaty): income is taxed where the work is physically done. Telework from France counts as performed <strong>in Switzerland up to 40 % of annual working time</strong> (Telework Protocol No. 1 para. a); Switzerland remits France 40 % of the tax on the telework share.</li></ul>
<p>Temporary assignments (business trips) in the state of residence or a third country count inside the 40 % — but only up to <strong>ten days per year</strong> in total (No. 3). Cross the 40 % line and the income is split under Art. 17 paras. 1–3 <strong>from the first telework day of the year</strong>: the telework share becomes taxable in the state of residence and the compensation falls away (No. 1 para. d). That is the expensive tipping effect — it reaches back over the whole year.</p>"""),
("Germany: no percentage cap, but 60 non-return days",
"""<p>Contrary to what is often read: the CH-DE treaty (SR 0.672.913.62) contains <strong>no telework provision at all</strong>. The percentages quoted around are social-security rules (see below). For tax, the treaty keeps:</p>
<ul><li><strong>Art. 15 (day principle):</strong> employment income is taxed where the work is physically done. Home-office days in Germany are worked in your state of residence and taxed there with your worldwide income; Switzerland taxes the days worked on its territory.</li><li><strong>Art. 15a (commuter privilege):</strong> Switzerland levies only <strong>4.5 % withholding tax</strong> on the gross salary (with the residence certificate, form Gre-1). This rate does not depend on the number of home-office days but on <strong>regular return</strong>: the status is lost only if you spend <strong>more than 60 working days</strong> per calendar year not returning home for work reasons (trips with overnight stays, on-call duty).</li><li>Per the competent-authority agreement, regular return exists if you travel from home to the workplace and back on <strong>at least 20 %</strong> of the contracted working days.</li></ul>
<p>Plain home-office: working from your German home is by definition a return to your residence — home-office days are <strong>not</strong> non-return days. Only work-related overnight stays away from home count against the 60-day budget.</p>"""),
("Social security: 25 / 49.9 % — same for DE, FR and IT",
"""<p>On the social-security track one regime applies to all neighbouring countries (multilateral framework agreement under Art. 16 of Regulation (EC) 883/2004, applied by Switzerland since 1 July 2023, for Italy since 1 January 2024):</p>
<ul><li><strong>Below 25 %</strong> telework in the state of residence: competence stays with Switzerland under the ordinary rules anyway.</li><li><strong>Between 25 and 49.9 %:</strong> Switzerland remains competent — but only if the employer requests an <strong>A1 certificate</strong> from the Swiss compensation fund via the ALPS platform (valid up to 3 years, renewable). Without the A1 you are insured in your country of residence.</li><li><strong>Above 50 %:</strong> the state of residence becomes competent.</li></ul>
<p>Key point: the framework agreement concerns <strong>social security only, not taxation</strong>. Exceeding the 40 % tax line with France or the 60-day line with Germany does not move you out of Swiss social insurance as long as telework stays under 49.9 % — and vice versa.</p>"""),
("Reporting and certificate duties since 2025",
"""<ul><li><strong>Employer certificate (Art. 5a of the Withholding Tax Ordinance, QStV):</strong> since 1 January 2025, upon a mid-year departure the former employer must, on the employee's request, issue a certificate of telework days/rate, temporary assignments in the state of residence and third countries, and overnight stays in Switzerland (ESTV form). Needed for the correct hand-over to the new employer.</li><li><strong>Automatic payroll data exchange CH-FR:</strong> the ESTV reports telework days/rate and gross remuneration of affected employees to France annually by <strong>30 November</strong> of the following year (Art. 28ter CH-FR treaty).</li></ul>"""),
("Practical: checklist per year",
"""<ol><li><strong>Count telework days and temporary assignments per calendar year</strong> (the employer is on the hook; keep your own record to be safe).</li><li>FR relation: stay under <strong>40 %</strong>, third/residence-state assignments under <strong>10 days</strong>.</li><li>DE relation: keep work-related <strong>overnight stays under 60</strong>, renew Gre-1 every year.</li><li>Social security: from 25 % telework, have the employer <strong>apply for the A1</strong>.</li><li>Changing jobs mid-year: <strong>request the Art. 5a QStV certificate</strong>.</li></ol>
<p class="muted">General information, not legal or tax advice. Only the treaty texts (fedlex AS 2025 486, SR 0.672.913.62) and the BSV/ESTV guidance are authoritative. Details depend on the canton of work and the individual case — clarify borderline situations early.</p>"""),
]

FR = [
(H2["fr"],
"""<p>Le frontalier qui travaille à domicile évolue sur deux plans juridiques distincts : le <strong>droit fiscal</strong> (quel État peut imposer son salaire ?) et le <strong>droit des assurances sociales</strong> (dans quel État est-il assuré ?). La plupart des erreurs viennent de ce que les règles d'un plan sont appliquées à l'autre. État des lieux 2026/2027, chaque point vérifié contre le texte primaire :</p>
<ul class="tick"><li><strong>France (fiscal) :</strong> trois régimes selon le canton de travail — l'accord de 1983 (huit cantons frontaliers : salaire imposable en France seulement, la Suisse reçoit une compensation de 4,5 %), le canton de Genève (imposition à la source intégrale en Suisse, versement de 3,5 % à l'Ain et la Haute-Savoie, seuil franchisable de 15 % pour le télétravail), et les autres cantons (CDI ordinaire). Dénominateur commun : la <strong>limite de 40 % de télétravail par année civile</strong> (convention additionnelle en vigueur depuis le 24 juillet 2025).</li><li><strong>Allemagne (fiscal) :</strong> la CDI CH-DE ne connaît <strong>aucune tolérance en pourcentage</strong>. C'est le principe journalier (art. 15) plus la limite de <strong>60 jours de non-retour</strong> (art. 15a al. 2).</li><li><strong>Assurances sociales (tous les pays voisins) :</strong> l'accord-cadre multilatéral permet jusqu'à <strong>49,9 % de télétravail</strong> sans changer d'affiliation — mais uniquement avec une <strong>attestation A1</strong>.</li></ul>"""),
("France : trois régimes — le canton de travail décide",
"""<p>Pour les frontaliers résidant en France, la répartition fiscale dépend du siège de l'employeur. Trois régimes, un dénominateur commun : la limite de 40 % de télétravail par année civile (applicable rétroactivement aux rémunérations versées dès le 1er janvier 2023, durablement depuis l'entrée en vigueur de la convention additionnelle le 24 juillet 2025).</p>
<ul><li><strong>Cantons de l'accord de 1983</strong> (BE, BL, BS, JU, NE, SO, VD, VS) : le salaire est imposable exclusivement en France ; la France verse à la Suisse une compensation de 4,5 % de la masse salariale brute. Le télétravail jusqu'à 40 % n'y change rien ; au-delà, le statut de frontalier est perdu.</li><li><strong>Canton de Genève</strong> (accord du 29 janvier 1973) : la Suisse impose le salaire intégralement à la source ; Genève verse chaque année 3,5 % de la masse salariale brute aux départements de l'Ain et de la Haute-Savoie. Pour la compensation liée au télétravail, un <strong>seuil de 15 %</strong> s'applique : rien n'est dû pour la part sous 15 %, seuls les jours entre 15 et 40 % sont compensés.</li><li><strong>Autres cantons</strong> (CDI ordinaire) : le revenu est imposable là où le travail est physiquement exercé. Le télétravail depuis la France est réputé exercé <strong>en Suisse jusqu'à 40 % du temps de travail annuel</strong> (protocole télétravail ch. 1 let. a) ; la Suisse reverse à la France 40 % de l'impôt perçu sur la part de télétravail.</li></ul>
<p>Les missions temporaires (déplacements professionnels) dans l'État de résidence ou un État tiers sont comptées dans les 40 % — mais seulement jusqu'à <strong>dix jours par année</strong> au total (ch. 3). Au-delà de 40 %, le revenu est réparti selon l'art. 17 al. 1–3 <strong>dès le premier jour de télétravail de l'année</strong> : la part de télétravail devient imposable dans l'État de résidence et la compensation tombe (ch. 1 let. d). C'est l'effet de bascule coûteux — il remonte à toute l'année.</p>"""),
("Allemagne : pas de pourcentage, mais 60 jours de non-retour",
"""<p>Contrairement à ce qu'on lit souvent : la CDI CH-DE (RS 0.672.913.62) ne contient <strong>aucune disposition sur le télétravail</strong>. Les pourcentages cités partout relèvent des assurances sociales (voir plus bas). Sur le plan fiscal, la convention garde :</p>
<ul><li><strong>Art. 15 (principe journalier) :</strong> le revenu d'emploi est imposable là où le travail est physiquement exercé. Les jours de télétravail en Allemagne sont travaillés dans l'État de résidence et imposés là avec le revenu mondial ; la Suisse impose les jours travaillés sur son territoire.</li><li><strong>Art. 15a (privilège du frontalier) :</strong> la Suisse ne perçoit que <strong>4,5 % d'impôt à la source</strong> sur le salaire brut (avec le certificat de résidence, formulaire Gre-1). Ce taux ne dépend pas du nombre de jours à domicile mais du <strong>retour régulier</strong> : le statut se perd seulement en cas de <strong>plus de 60 jours de travail</strong> par année civile sans retour au domicile pour des raisons professionnelles (déplacements avec nuitée, astreinte).</li><li>Selon l'accord amiable, le retour est régulier si l'employé effectue le trajet domicile-travail aller-retour au moins <strong>20 %</strong> des jours de travail convenus.</li></ul>
<p>Télétravail pur : travailler depuis son domicile allemand constitue par définition un retour au domicile — les jours de télétravail ne sont <strong>pas</strong> des jours de non-retour. Seules les nuitées professionnelles hors du domicile comptent dans le budget de 60 jours.</p>"""),
("Assurances sociales : 25 / 49,9 % — identique pour DE, FR et IT",
"""<p>Sur le plan des assurances sociales, un seul régime vaut pour tous les pays voisins (accord-cadre multilatéral fondé sur l'art. 16 du règlement (CE) 883/2004, appliqué par la Suisse depuis le 1er juillet 2023, pour l'Italie depuis le 1er janvier 2024) :</p>
<ul><li><strong>Moins de 25 %</strong> de télétravail dans l'État de résidence : la compétence reste suisse selon les règles ordinaires.</li><li><strong>Entre 25 et 49,9 % :</strong> la Suisse reste compétente — mais uniquement si l'employeur demande une <strong>attestation A1</strong> à la caisse de compensation suisse via la plateforme ALPS (valable jusqu'à 3 ans, renouvelable). Sans A1, vous êtes assuré dans votre État de résidence.</li><li><strong>Au-delà de 50 % :</strong> l'État de résidence devient compétent.</li></ul>
<p>Point clé : l'accord-cadre ne concerne <strong>que les assurances sociales, pas la fiscalité</strong>. Dépasser la ligne fiscale des 40 % avec la France ou celle des 60 jours avec l'Allemagne ne change rien à l'affiliation suisse tant que le télétravail reste sous 49,9 % — et inversement.</p>"""),
("Obligations déclaratives depuis 2025",
"""<ul><li><strong>Attestation de l'employeur (art. 5a OIS) :</strong> depuis le 1er janvier 2025, en cas de départ en cours d'année, l'ancien employeur doit délivrer sur demande au travailleur résidant en France une attestation portant sur les jours de télétravail ou le taux de télétravail, les missions temporaires dans l'État de résidence et les États tiers, ainsi que les nuitées en Suisse (formulaire AFC). Nécessaire pour la reprise correcte par le nouvel employeur.</li><li><strong>Échange automatique de données salariales CH-FR :</strong> l'AFC communique à la France, chaque année jusqu'au <strong>30 novembre</strong> de l'année suivante, les jours/taux de télétravail et les rémunérations brutes des travailleurs concernés (art. 28ter CDI CH-FR).</li></ul>"""),
("En pratique : check-list par année",
"""<ol><li><strong>Dénombrer les jours de télétravail et les missions temporaires par année civile</strong> (l'employeur est tenu de le faire ; gardez vos propres relevés).</li><li>Relation FR : rester sous <strong>40 %</strong>, missions sous <strong>10 jours</strong>.</li><li>Relation DE : garder les <strong>nuitées professionnelles sous 60</strong>, renouveler le Gre-1 chaque année.</li><li>Assurances sociales : dès 25 % de télétravail, faire demander <strong>l'attestation A1</strong> par l'employeur.</li><li>Changement d'employeur en cours d'année : <strong>exiger l'attestation art. 5a OIS</strong>.</li></ol>
<p class="muted">Informations générales, sans conseil juridique ou fiscal. Seuls les textes conventionnels (fedlex AS 2025 486, RS 0.672.913.62) et les directives de l'OFAS et de l'AFC font foi. Les détails dépendent du canton d'activité et du cas d'espèce — clarifiez tôt les situations limites.</p>"""),
]

IT = [
(H2["it"],
"""<p>Il frontaliero che lavora da casa si muove su due binari giuridici distinti: il <strong>diritto fiscale</strong> (quale Stato può tassare il salario?) e il <strong>diritto delle assicurazioni sociali</strong> (in quale Stato è assicurato?). La maggior parte degli errori nasce dall'applicare le regole di un binario all'altro. Quadro 2026/2027, ogni punto verificato sul testo primario:</p>
<ul class="tick"><li><strong>Francia (fiscale):</strong> tre regimi a seconda del cantone di lavoro — l'accordo del 1983 (otto cantoni di frontiera: salario imponibile solo in Francia, alla Svizzera spetta un compenso del 4,5 %), il cantone Ginevra (imposta alla fonte integrale in Svizzera, versamento del 3,5 % ad Ain e Alta Savoia, franchigia del 15 % per il telelavoro), e gli altri cantoni (CDI ordinaria). Elemento comune: il <strong>limite del 40 % di telelavoro per anno civile</strong> (accordo addizionale in vigore dal 24 luglio 2025).</li><li><strong>Germania (fiscale):</strong> la CDI CH-DE non prevede <strong>nessuna tolleranza percentuale</strong>. Valgono il principio giornaliero (art. 15) e il limite di <strong>60 giorni di non ritorno</strong> (art. 15a cpv. 2).</li><li><strong>Assicurazioni sociali (tutti i Paesi confinanti):</strong> l'accordo quadro multilaterale consente fino al <strong>49,9 % di telelavoro</strong> senza cambio di assicurazione — ma solo con <strong>attestato A1</strong>.</li></ul>"""),
("Francia: tre regimi — decide il cantone di lavoro",
"""<p>Per i frontalieri residenti in Francia, la ripartizione fiscale dipende dalla sede del datore di lavoro. Tre regimi, un denominatore comune: il limite del 40 % di telelavoro per anno civile (applicabile retroattivamente ai compensi versati dal 1° gennaio 2023, in via stabile dall'entrata in vigore dell'accordo addizionale il 24 luglio 2025).</p>
<ul><li><strong>Cantoni dell'accordo del 1983</strong> (BE, BL, BS, JU, NE, SO, VD, VS): il salario è imponibile esclusivamente in Francia; la Francia versa alla Svizzera un compenso del 4,5 % della massa salariale lorda. Il telelavoro fino al 40 % non cambia nulla; oltre tale soglia lo status di frontaliero si perde.</li><li><strong>Cantone Ginevra</strong> (accordo del 29 gennaio 1973): la Svizzera impone integralmente il salario alla fonte; Ginevra versa ogni anno il 3,5 % della massa salariale lorda ai dipartimenti Ain e Alta Savoia. Per il compenso legato al telelavoro vale una <strong>franchigia del 15 %</strong>: è dovuto solo per i giorni di telelavoro compresi tra il 15 e il 40 %.</li><li><strong>Altri cantoni</strong> (CDI ordinaria): il reddito è tassato dove l'attività è fisicamente svolta. Il telelavoro dalla Francia è considerato svolto <strong>in Svizzera fino al 40 % dell'orario annuale</strong> (protocollo telelavoro n. 1 lett. a); la Svizzera riversa alla Francia il 40 % dell'imposta sulla quota di telelavoro.</li></ul>
<p>Nel 40 % rientrano anche le missioni temporanee (trasferte) nello Stato di domicilio o in uno Stato terzo — ma solo fino a <strong>dieci giorni per anno</strong> in totale (n. 3). Oltre il 40 %, il reddito è ripartito secondo l'art. 17 cpv. 1–3 <strong>dal primo giorno di telelavoro dell'anno</strong>: la quota di telelavoro diventa imponibile nello Stato di residenza e il compenso decade (n. 1 lett. d). È il costoso effetto di scatto — vale per tutto l'anno.</p>"""),
("Germania: nessuna percentuale, ma 60 giorni di non ritorno",
"""<p>Contrariamente a quanto spesso si legge: la CDI CH-DE (RS 0.672.913.62) non contiene <strong>alcuna disposizione sul telelavoro</strong>. Le percentuali citate riguardano le assicurazioni sociali (vedi sotto). Sul piano fiscale valgono:</p>
<ul><li><strong>Art. 15 (principio giornaliero):</strong> il reddito da lavoro dipendente è tassato dove l'attività è fisicamente svolta. I giorni di lavoro da casa in Germania sono svolti nello Stato di domicilio e lì tassati con il reddito mondiale; la Svizzera tassa i giorni lavorati sul suo territorio.</li><li><strong>Art. 15a (privilegio del frontaliero):</strong> la Svizzera percepisce solo il <strong>4,5 % d'imposta alla fonte</strong> sul salario lordo (con certificato di domicilio, modulo Gre-1). L'aliquota non dipende dai giorni di lavoro da casa ma dal <strong>rientro regolare</strong>: lo status si perde solo oltre <strong>60 giorni di lavoro</strong> per anno civile senza rientro al domicilio per motivi professionali (trasferte con pernottamento, reperibilità).</li><li>Secondo l'accordo amichevole il rientro è regolare se il lavoratore effettua il tragitto casa-lavoro di andata e ritorno almeno nel <strong>20 %</strong> dei giorni di lavoro pattuiti.</li></ul>
<p>Telelavoro puro: lavorare da casa in Germania è per definizione un rientro al domicilio — i giorni di telelavoro <strong>non</strong> sono giorni di non ritorno. Contano nel budget dei 60 giorni solo i pernottamenti professionali fuori domicilio.</p>"""),
("Assicurazioni sociali: 25 / 49,9 % — identico per DE, FR e IT",
"""<p>Sul binario delle assicurazioni sociali vale un unico regime per tutti i Paesi confinanti (accordo quadro multilaterale ai sensi dell'art. 16 del regolamento (CE) 883/2004, applicato dalla Svizzera dal 1° luglio 2023, per l'Italia dal 1° gennaio 2024):</p>
<ul><li><strong>Sotto il 25 %</strong> di telelavoro nello Stato di domicilio: la competenza resta svizzera secondo le regole ordinarie.</li><li><strong>Tra il 25 e il 49,9 %:</strong> la Svizzera resta competente — ma solo se il datore di lavoro chiede l'<strong>attestato A1</strong> alla cassa di compensazione svizzera tramite la piattaforma ALPS (valido fino a 3 anni, rinnovabile). Senza A1 si è assicurati nello Stato di domicilio.</li><li><strong>Oltre il 50 %:</strong> diventa competente lo Stato di domicilio.</li></ul>
<p>Punto chiave: l'accordo quadro riguarda <strong>solo le assicurazioni sociali, non la fiscalità</strong>. Superare la linea fiscale del 40 % con la Francia o quella dei 60 giorni con la Germania non toglie l'assicurazione svizzera finché il telelavoro resta sotto il 49,9 % — e viceversa.</p>"""),
("Obblighi di comunicazione dal 2025",
"""<ul><li><strong>Attestato del datore di lavoro (art. 5a OIF):</strong> dal 1° gennaio 2025, in caso di uscita a metà anno, il precedente datore di lavoro deve rilasciare su richiesta al lavoratore domiciliato in Francia un attestato sui giorni di telelavoro o sul tasso di telelavoro, sulle missioni temporanee nello Stato di domicilio e in Stati terzi e sui pernottamenti in Svizzera (modulo AFC). Necessario per il corretto subentro del nuovo datore di lavoro.</li><li><strong>Scambio automatico di dati salariali CH-FR:</strong> l'AFC comunica alla Francia, ogni anno entro il <strong>30 novembre</strong> dell'anno successivo, giorni/tasso di telelavoro e compensi lordi dei lavoratori interessati (art. 28ter CDI CH-FR).</li></ul>"""),
("In pratica: check-list per anno",
"""<ol><li><strong>Contare i giorni di telelavoro e le missioni per anno civile</strong> (obbligo del datore di lavoro; tenere comunque propri riscontri).</li><li>Rapporto FR: restare sotto il <strong>40 %</strong>, missioni sotto <strong>10 giorni</strong>.</li><li>Rapporto DE: mantenere i <strong>pernottamenti professionali sotto 60</strong>, rinnovare il Gre-1 ogni anno.</li><li>Assicurazioni sociali: dal 25 % di telelavoro, far chiedere l'<strong>attestato A1</strong> dal datore di lavoro.</li><li>Cambio di datore di lavoro in corso d'anno: <strong>esigere l'attestato art. 5a OIF</strong>.</li></ol>
<p class="muted">Informazioni generali, non consulenza giuridica o fiscale. Fanno fede soltanto i testi convenzionali (fedlex AS 2025 486, RS 0.672.913.62) e le direttive di UFS e AFC. I dettagli dipendono dal cantone di attività e dal caso concreto — chiarire per tempo le situazioni limite.</p>"""),
]

if __name__ == "__main__":
    for lang, sections in (("de", DE), ("en", EN), ("fr", FR), ("it", IT)):
        build(lang, SLUG, TITLE[lang], META[lang], sections, related=RELATED)
    print("done")
