#!/usr/bin/env python3
"""One-shot publish batch 2026-09-30: verrechnungssteuer-rueckerstattungsfrist-ablauf (de/en/fr/it)."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from article_template import build

SLUG = "verrechnungssteuer-rueckerstattungsfrist-ablauf"

# ---------------- DE ----------------
de_title = "Verrechnungssteuer 2023: Rückforderung verfällt am 31. Dezember 2026"
de_meta = "Die 35 % Verrechnungssteuer auf 2023er-Dividenden und -Zinsen sind endgültig verloren, wenn der Antrag nicht bis am 31. Dezember 2026 gestellt wird (Art. 32 Abs. 1 VStG). So prüfen Sie Ihr Depot und holen Sie Ihr Geld zurück."
de_secs = [
 ("Warum jetzt Frist ist: die Verwirkungsfrist von drei Jahren",
  """<p>Jede Dividende und jeder Zinsertrag aus Schweizer Quellen wird an der Quelle mit 35 % Verrechnungssteuer belastet (Art. 13 VStG). Bank oder Gesellschaft behalten den Abzug ein und liefern ihn an die Eidgenössische Steuerverwaltung (ESTV) ab. Zurückholen lässt sich das Geld nur auf Antrag – und das Recht darauf ist befristet: «Der Anspruch auf Rückerstattung erlischt, wenn der Antrag nicht innert drei Jahren nach Ablauf des Kalenderjahres, in dem die steuerbare Leistung fällig geworden ist, gestellt wird» (Art. 32 Abs. 1 VStG).</p>
<p>Für Erträge aus dem Jahr 2023 läuft diese Frist am 31. Dezember 2026 ab. Es handelt sich um eine Verwirkungsfrist, die – wie die ESTV ausdrücklich festhält – grundsätzlich weder unterbrochen noch verlängert werden kann. Wer 2023er-Dividenden oder -Zinsen nie deklariert hat und bis Ende Jahr nichts unternimmt, verliert die belasteten 35 % endgültig.</p>
<p>Die nächsten Countdowns folgen in jährlichem Takt: Für die Erträge von 2024 endet die Frist am 31. Dezember 2027, für jene von 2025 am 31. Dezember 2028. Wer das Prinzip einmal verstanden hat, kann die Prüfung zur Jahresendroutine machen.</p>
<p><strong>Praxistipp:</strong> Notieren Sie sich den 31. Dezember als festen Prüfungstermin im Kalender – jede Steuerperiode hat ihren eigenen Verfalltag, und keiner lässt sich nachträglich verschieben.</p>"""),
 ("Der einfache Weg: Deklaration in der Steuererklärung",
  """<p>Wer ordentlich veranlagt wird, hat den Antrag praktisch schon gestellt: Die Deklaration der Erträge im Wertschriftenverzeichnis der Steuererklärung wirkt als Rückerstattungsgesuch beim Wohnsitzkanton (Art. 30 VStG). Die Steuerbehörde vergütet die Verrechnungssteuer in der Veranlagung automatisch – vorausgesetzt, die Erträge sind vollständig und brutto deklariert, also inklusive der abgezogenen 35 %.</p>
<p>Der klassische Fehlerfall sind Depot-Erträge, die in der Steuererklärung schlicht fehlen: übersehene Titel, «vergessene» Dividenden kleiner Beteiligungen oder Konten, von denen niemand glaubte, dass sie die Steuerbehörde sehen. Durch den automatischen Informationsaustausch (AIA) mit den meisten Partnerstaaten fallen solche Lücken bei Nachforschungen laufend auf – und ohne Deklaration gibt es keine Rückerstattung.</p>
<p>Wichtig, die zwei Baustellen sauber zu trennen: Eine nachgeholte 2023er-Deklaration kann die Verrechnungssteuer noch binnen Frist bringen, löst aber für das bisher unversteuerte Einkommen eine Nachsteuer aus. Für die Vergangenheit greift die straflose Selbstanzeige: Wer erstmals eine Steuerhinterziehung selbst anzeigt, muss keine Busse fürchten – es bleiben Nachsteuer plus Verzugszins geschuldet (Art. 175 Abs. 3 DBG); bei jeder weiteren Selbstanzeige wird die Busse auf einen Fünftel der hinterzogenen Steuer ermässigt (Art. 175 Abs. 4). Wer sich hier unsicher ist, sollte die Konstellation vor der Einreichung prüfen lassen.</p>
<p><strong>Praxistipp:</strong> Ziehen Sie für 2023 die Jahresend- und Dividendenausweise aller Banken und Depotstellen bei – einzeln, auch von Konten, die Sie kaum noch benutzen. Die Brutto-Aufstellung der fälligen Leistungen zeigt auf einen Blick, ob jeder Titel in der Erklärung gelandet ist.</p>"""),
 ("Ohne automatische Verrechnung: das Rückerstattungsverfahren",
  """<p>Nicht in jedem Fall greift die automatische Verrechnung über die Veranlagung: Wer keine Steuererklärung einreichen muss oder kann, wer zwischenzeitlich wegzog oder verstorben ist, oder wer Erträge erhielt, die in keiner Veranlagung auftauchten, stellt den Antrag schriftlich bei der ESTV – am einfachsten über das ESTV-Portal oder mit dem elektronischen Formular 25 «Antrag auf Rückerstattung der Verrechnungssteuer». Die gedruckten Formulare sind nicht mehr erhältlich; der Antrag kann frühestens nach Ablauf des Kalenderjahres gestellt werden, in dem die Leistung fällig wurde (Art. 29 VStG). Beizulegen sind Nachweise über die steuerbare Leistung, etwa der Jahresendauszug des Depots.</p>
<p>Der Antrag muss bis zum 31. Dezember 2026 gestellt sein. Die ESTV bestätigt den Eingang von Rückerstattungsanträgen nicht; online gestellte Anträge lassen sich im Portal jederzeit in ihrem Status prüfen. Sicherer ist die elektronische Einreichung mit nachvollziehbarer Referenz noch vor den Festtagen, wenn Behörden und Postwerke unter Hochdruck arbeiten.</p>
<p>Für Erbschaften gilt: Die Verwirkungsfrist läuft für die Erträge einer verstorbenen Person weiter. Wer einen Nachlass verwaltet, sollte die Depots auf offene VST-Rückerstattungen der letzten drei Jahre prüfen, bevor die Ansprüche nacheinander verfallen.</p>
<p><strong>Praxistipp:</strong> Bewahren Sie den Auszug des Portals bzw. die Antragskopie mit Einreichedatum bis zum Abschluss der Rückzahlung auf – im Streitfall zählt allein der Nachweis, dass der Antrag vor dem 31. Dezember eingereicht wurde.</p>"""),
 ("Was die Frist nicht heilt: die angrenzenden Töpfe",
  """<p>Nicht alles, was nach 35 % aussieht, ist eidgenössische Verrechnungssteuer: Sie wird nur auf steuerbaren Schweizer Leistungen erhoben – Dividenden, Gewinnanteile, Zinsen und bestimmte geldwerte Leistungen bei nahe stehenden Kapitalgesellschaften. Erträge aus ausländischen Titeln unterliegen nicht der CH-Verrechnungssteuer; dort geht es um die ausländische Quellensteuer, die über das Ergänzungsblatt DA-1 der Steuererklärung angerechnet wird – ein anderes Regime mit anderen Regeln.</p>
<p>Zweitens setzt jede Rückerstattung voraus, dass die Erträge deklariert und die Einkünfte versteuert werden. Die Verrechnungssteuer wird bei korrekter Veranlagung voll vergütet; wer die Erträge verschweigt, lässt das Geld faktisch liegen – und riskiert zusätzlich die Nachbesteuerung.</p>
<p>Drittens läuft bei Fonds und kollektiven Kapitalanlagen die Rückerstattung der auf Fondsstufe belasteten Verrechnungssteuer in der Regel über die Fondsleitung, nicht über die einzelne Anlegerin bzw. den einzelnen Anleger im Privatvermögen. Und schliesslich: Ein Depot, das erst 2024 eröffnet wurde, wirft die 2023-Frage nicht auf – prüfen Sie dennoch ältere Konten, Sparkapitalien und polizenähnliche Anlagen.</p>
<p><strong>Praxistipp:</strong> Trennen Sie die Töpfe sauber: 35 % CH-Verrechnungssteuer (2023er-Erträge: Antrag bis 31.12.2026), ausländische Quellensteuer (DA-1, keine VStG-Frist), Fondsvermögen (Weg über die Fondsleitung) – drei Regime, drei Prüfpfade.</p>"""),
 ("Rechenbeispiel: was auf dem Spiel steht",
  """<p>Ein mittelgrosses Depot mit CHF 20'000 Bruttoertrag aus Dividenden und Zinsen im Jahr 2023 wurde mit CHF 7'000 Verrechnungssteuer belastet. Wurde dieses Depot nie deklariert und bis am 31. Dezember 2026 kein Antrag gestellt, sind die CHF 7'000 verloren – unabhängig davon, dass auf die Erträge ohnehin die Einkommensteuer geschuldet bleibt.</p>
<p>Umgekehrt: Bei Deklaration in der Steuererklärung 2023 – oder einer nachgeholten 2023er-Veranlagung vor Fristablauf – werden die CHF 7'000 vergütet bzw. angerechnet; die Steuer auf den Erträgen fällt dabei an, netto bleibt aber deutlich mehr als bei Verwirkung. Für ein Ehepaar mit einem gemeinsamen Depot verdoppelt sich der Prüfaufwand kaum – der potenzielle Rückzahlungsbetrag dagegen schon.</p>
<p>Legen Sie sich die Zahlen vor dem Entscheiden zurecht: Bruttoertrag, belastete VST, erwartete Einkommensteuerwirkung, und ob eine Nachsteuer im Raum steht. Der Aufwand für einen Portal-Antrag ist überschaubar; die Beträge sind es oft nicht.</p>
<p><strong>Praxistipp:</strong> Prüfen Sie zuerst die Depots, die Sie nicht mehr selbst verwalten – Kinder-Depots, alte Freizügigkeits- und Sparkonten, verzinsliche Policen. Die häufigsten Verfallsfälle sind Titel, an die nach dem letzten Bankwechsel niemand mehr dachte.</p>"""),
 ("Kurz gesagt",
  """<ul><li>Art. 32 Abs. 1 VStG: Der Rückerstattungsanspruch für 2023er-Dividenden und -Zinsen erlischt am 31. Dezember 2026 – Verwirkungsfrist, grundsätzlich weder unterbrochen noch verlängert.</li>
<li>Ordentlich Veranlagte deklarieren die Erträge brutto im Wertschriftenverzeichnis; die Deklaration wirkt als Rückerstattungsgesuch (Art. 30 VStG).</li>
<li>Direktgesuch bei der ESTV: ESTV-Portal oder elektronisches Formular 25; Antrag frühestens nach Ablauf des Fälligkeitsjahres (Art. 29 VStG), Eingang vor dem 31.12.2026.</li>
<li>Ausländische Quellensteuer ist ein anderes Regime (DA-1); bei Fonds läuft die Rückerstattung über die Fondsleitung.</li>
<li>Nächste Fristen: 2024er-Erträge bis 31.12.2027, 2025er-Erträge bis 31.12.2028.</li></ul>"""),
]

# ---------------- EN ----------------
en_title = "Swiss withholding tax 2023: reclaims expire on 31 December 2026"
en_meta = "The 35 % Swiss withholding tax (Verrechnungssteuer) on 2023 dividends and interest is lost for good unless a claim is filed by 31 December 2026 (Art. 32 para. 1 WHTA). How to check your portfolio and get your money back."
en_secs = [
 ("Why the clock is ticking: the three-year forfeiture period",
  """<p>Every dividend and interest payment from Swiss sources is charged 35 % withholding tax at source (Art. 13 of the Federal Act on Withholding Tax, WHTA/VStG). The bank or company retains the deduction and remits it to the Federal Tax Administration (FTA/ESTV). The money is only returned on request – and the right to request it expires: the refund claim lapses if no application is made within three years after the end of the calendar year in which the taxable payment fell due (Art. 32 para. 1 WHTA).</p>
<p>For 2023 income, that deadline is 31 December 2026. The FTA states expressly that this is a forfeiture period which, as a rule, can be neither interrupted nor extended. Dividends or interest from 2023 that were never declared – and for which nothing is done by year-end – are lost permanently.</p>
<p>The next countdowns follow in yearly rhythm: 2024 income until 31 December 2027, 2025 income until 31 December 2028. Once you have understood the pattern, the check becomes an end-of-year routine.</p>
<p><strong>Practical tip:</strong> Put 31 December in your calendar as a fixed review date – every tax period carries its own expiry date, and none of them moves.</p>"""),
 ("The easy route: declaring it in your tax return",
  """<p>If you are assessed under the ordinary procedure, you have effectively already filed the claim: declaring the income in the securities schedule of your cantonal tax return acts as the refund request with your canton of residence (Art. 30 WHTA). The tax authority credits the withholding tax automatically in the assessment – provided the income is declared in full, gross, including the 35 % withheld.</p>
<p>The classic failure case is portfolio income simply missing from the return: overlooked securities, forgotten dividends from small holdings, or accounts nobody expected the tax office to see. With the automatic exchange of information (AEOI) in place with most partner states, such gaps surface regularly in follow-up assessments – and without a declaration there is no refund.</p>
<p>Keep the two workstreams apart: a belatedly filed 2023 return can still recover the withholding tax within the deadline, but it triggers back taxation on the previously untaxed income. For past concealment, the first voluntary disclosure of tax evasion is penalty-free: only back tax plus default interest remain owed (Art. 175 para. 3 of the Federal Act on Direct Federal Tax); on any further disclosure the penalty is reduced to one fifth of the tax evaded (Art. 175 para. 4). If the constellation is unclear, have it reviewed before filing.</p>
<p><strong>Practical tip:</strong> Pull the 2023 year-end and dividend statements from every bank and platform you have ever used – including accounts you barely touch. The gross list of due payments shows at a glance whether every security made it onto your return.</p>"""),
 ("Without automatic assessment: the direct refund procedure",
  """<p>The automatic credit via assessment does not cover every case: those who do not file a tax return, who moved abroad or died in the meantime, or who received income that never appeared in any assessment must apply in writing to the FTA – most easily via the ESTV portal or the electronic form 25 «Application for refund of withholding tax» (paper forms are no longer available; an application may be filed no earlier than after the end of the calendar year in which the payment became due – Art. 29 WHTA). Attach proof of the taxable payment, such as the year-end portfolio statement.</p>
<p>The application must be filed by 31 December 2026. The FTA does not confirm receipt of refund applications; applications submitted online can be tracked at any time in the portal. Filing electronically with a retrievable reference before the holiday season is the safer course.</p>
<p>For estates: the forfeiture period keeps running on a deceased person's income. Whoever administers an estate should review the depots for open withholding-tax claims of the last three years before they expire one by one.</p>
<p><strong>Practical tip:</strong> Keep the portal extract or a copy of the application with its filing date until the refund is complete – in a dispute, only proof that the claim was filed before 31 December counts.</p>"""),
 ("What the deadline does not fix: the neighbouring pots",
  """<p>Not everything that looks like 35 % is Swiss withholding tax: it applies only to taxable Swiss-source payments – dividends, profit shares, interest and certain monetised benefits from closely held companies. Income from foreign securities bears no Swiss withholding tax; there the issue is foreign withholding tax, credited via the DA-1 schedule of your tax return – a different regime with different rules.</p>
<p>Second, every refund presupposes that the income is declared and taxed. Under a correct assessment the withholding tax is fully credited; concealing the income simply lets the money lie where it is – while adding back-tax risk on top.</p>
<p>Third, for collective investment schemes the refund of withholding tax charged at fund level generally runs through the fund management, not through the individual holder of fund units in private wealth. And a depot opened only in 2024 has no 2023 question at all – though you should still review older accounts, savings capital and interest-bearing policies.</p>
<p><strong>Practical tip:</strong> Keep the pots separate: 35 % Swiss withholding tax (2023 income: claim by 31.12.2026), foreign withholding tax (DA-1, no WHTA deadline), fund assets (via the fund management) – three regimes, three checklists.</p>"""),
 ("Quick check: the size of the stake",
  """<p>A mid-sized portfolio with CHF 20,000 of gross 2023 dividend and interest income carried CHF 7,000 of withholding tax. If it was never declared and no claim is filed by 31 December 2026, those CHF 7,000 are gone – regardless of the income tax that is owed on the earnings anyway.</p>
<p>The inverse: declared in the 2023 return (or a belatedly filed 2023 assessment before the deadline), the CHF 7,000 are credited; income tax on the same earnings is due, but the net position is clearly better than forfeiting. For a married couple with one joint depot the workload hardly doubles – the potential refund does.</p>
<p>Do the arithmetic before deciding: gross income, tax withheld, expected income-tax effect, and whether back tax is on the table. The effort for a portal application is modest; the amounts often are not.</p>
<p><strong>Practical tip:</strong> Start with the portfolios you no longer manage – children's accounts, old vested-profit and savings accounts, interest-bearing insurance policies. The most common forfeitures concern securities nobody thought of after the last bank switch.</p>"""),
 ("In short",
  """<ul><li>Art. 32 para. 1 WHTA: refund claims for 2023 dividends and interest expire on 31 December 2026 – a forfeiture period, as a rule neither interruptible nor extendable.</li>
<li>Ordinarily assessed taxpayers declare gross income in the securities schedule; the declaration itself is the refund request (Art. 30 WHTA).</li>
<li>Direct claim to the FTA: ESTV portal or electronic form 25; filing possible from the year after the payment became due (Art. 29 WHTA), must arrive before 31.12.2026.</li>
<li>Foreign withholding tax is a different regime (DA-1); fund-level refunds run through the fund management.</li>
<li>Next deadlines: 2024 income by 31.12.2027, 2025 income by 31.12.2028.</li></ul>"""),
]

# ---------------- FR ----------------
fr_title = "Impôt anticipé 2023 : les remboursements prescrits au 31 décembre 2026"
fr_meta = "L'impôt anticipé de 35 % sur les dividendes et intérêts 2023 est définitivement perdu si aucune demande n'est déposée jusqu'au 31 décembre 2026 (art. 32 al. 1 LIA). Comment vérifier votre dépôt et récupérer votre argent."
fr_secs = [
 ("Pourquoi l'échéance approche : le délai de trois ans",
  """<p>En Suisse, chaque dividende et intérêt de source suisse est grevé à la source d'un impôt anticipé de 35 % (art. 13 de la loi fédérale sur l'impôt anticipé, LIA). La banque ou la société retient le prélèvement et le verse à l'Administration fédérale des contributions (AFC). L'argent n'est restitué que sur demande – et le droit de la formuler s'éteint : « Le droit au remboursement s'éteint si la demande n'est pas faite dans les trois ans qui suivent la fin de l'année civile au cours de laquelle la prestation imposable a été due » (art. 32 al. 1 LIA).</p>
<p>Pour les revenus 2023, ce délai échoit le 31 décembre 2026. L'AFC souligne expressément qu'il s'agit d'un délai de forclusion qui, en principe, ne peut être ni interrompu ni prolongé. Dividendes et intérêts 2023 jamais déclarés, pour lesquels rien n'est entrepris jusqu'à fin année, sont définitivement perdus.</p>
<p>Les compteurs suivants suivent un rythme annuel : revenus 2024 jusqu'au 31 décembre 2027, revenus 2025 jusqu'au 31 décembre 2028. Une fois la logique comprise, la vérification devient une routine de fin d'année.</p>
<p><strong>Conseil pratique :</strong> inscrivez le 31 décembre dans votre calendrier comme date fixe de contrôle – chaque période fiscale a son échéance propre, et aucune ne se déplace après coup.</p>"""),
 ("La voie simple : la déclaration dans le retour d'impôt",
  """<p>Qui est taxé selon la procédure ordinaire a en pratique déjà déposé la demande : déclarer les revenus dans l'état des titres de la déclaration d'impôt cantonale vaut demande de remboursement auprès du canton de domicile (art. 30 LIA). L'autorité fiscale impute l'impôt anticipé d'office lors de la taxation – à condition de déclarer les revenus intégralement, en brut, impôt de 35 % compris.</p>
<p>Le cas d'échec classique : les titres absents de la déclaration – actions oubliées, petits dividendes, comptes que l'on croyait invisibles. Depuis l'échange automatique de renseignements (EAR) avec la plupart des États partenaires, ces lacunes surgissent régulièrement lors de taxations ultérieures – et sans déclaration, pas de remboursement.</p>
<p>Séparez les deux chantiers : une déclaration 2023 régularisée dans les délais peut encore récupérer l'impôt anticipé, mais elle déclenche un impôt rappelé sur le revenu jusqu'alors non imposé. Pour les dissimulations passées, la première dénonciation spontanée est sans peine : celui qui dénonce lui-même une soustraction fiscale pour la première fois ne risque pas d'amende – seuls l'impôt dû et les intérêts moratoires restent dus (art. 175 al. 3 LIFD) ; pour toute dénonciation ultérieure, l'amende est réduite au cinquième de l'impôt soustrait (art. 175 al. 4). En cas de doute sur la configuration, faites examiner le dossier avant de déposer.</p>
<p><strong>Conseil pratique :</strong> exigez pour 2023 les décomptes annuels et de dividendes de toutes vos banques et plateformes – y compris les comptes que vous n'utilisez presque plus. La liste brute des prestations dues montre d'un coup d'œil si chaque titre a bien figuré dans votre déclaration.</p>"""),
 ("Sans imputation automatique : la procédure de restitution directe",
  """<p>L'imputation automatique via la taxation ne couvre pas tous les cas : qui ne dépose pas de déclaration, a changé de domicile ou est décédé entre-temps, ou a perçu des revenus n'apparaissant dans aucune taxation, adresse la demande par écrit à l'AFC – le plus simplement via le portail ESTV ou le formulaire électronique 25 « Demande en remboursement de l'impôt anticipé » (les formulaires imprimés ne sont plus disponibles ; la demande peut être déposée au plus tôt après la fin de l'année civile de la prestation – art. 29 LIA). Joignez les justificatifs de la prestation imposable, par exemple le relevé de titres de fin d'année.</p>
<p>La demande doit être déposée jusqu'au 31 décembre 2026. L'AFC ne confirme pas la réception des demandes de remboursement ; les demandes déposées en ligne sont consultables à tout moment dans le portail quant à leur état. Le dépôt électronique avec référence vérifiable avant les fêtes est la voie la plus sûre.</p>
<p>Pour les successions : le délai court sans arrêt pour les revenus d'une personne décédée. Qui administre une succession doit vérifier les dépôts pour d'éventuelles créances de restitution non réclamées des trois dernières années, avant qu'elles ne se prescrivent l'une après l'autre.</p>
<p><strong>Conseil pratique :</strong> conservez l'extrait du portail ou une copie de la demande portant sa date de dépôt jusqu'au versement du remboursement – en cas de litige, seule la preuve d'un dépôt avant le 31 décembre compte.</p>"""),
 ("Ce que l'échéance ne guérit pas : les pots voisins",
  """<p>Tout ne se ressemble : l'impôt anticipé suisse de 35 % ne frappe que les prestations suisses imposables – dividendes, parts de bénéfice, intérêts et certains avantages monétaires de sociétés à participation rapprochée. Les titres étrangers ne supportent pas d'impôt anticipé fédéral ; là, c'est l'impôt à la source étranger et son imputation via l'annexe DA-1 de la déclaration qui entrent en ligne de compte – un autre régime, d'autres règles.</p>
<p>Deuxièmement, tout remboursement présuppose que les revenus sont déclarés et imposés. Dans une taxation correcte, l'impôt anticipé est intégralement restitué ; taire les revenus laisse simplement l'argent où il est – avec en plus le risque d'un rappel d'impôt.</p>
<p>Troisièmement, pour les placements collectifs, la restitution de l'impôt anticipé perçu au niveau du fonds passe en règle générale par la direction du fonds, non par le détenteur privé de parts. Et un dépôt ouvert seulement en 2024 ne pose aucune question 2023 – vérifiez malgré tout vos anciens comptes, avoirs d'épargne et polices à rendement.</p>
<p><strong>Conseil pratique :</strong> gardez les pots séparés : 35 % d'impôt anticipé CH (revenus 2023 : demande jusqu'au 31.12.2026), impôt à la source étranger (DA-1, pas de délai LIA), avoirs en fonds (voie de la direction du fonds) – trois régimes, trois listes de contrôle.</p>"""),
 ("Vérification rapide : l'enjeu financier",
  """<p>Un dépôt moyen générant CHF 20'000 brut de dividendes et intérêts en 2023 a supporté CHF 7'000 d'impôt anticipé. Jamais déclaré, sans demande déposée jusqu'au 31 décembre 2026, ces CHF 7'000 sont perdus – indépendamment de l'impôt sur le revenu dû de toute façon sur ces gains.</p>
<p>L'inverse : déclarés dans la taxation 2023 (ou une taxation régularisée avant l'échéance), les CHF 7'000 sont imputés ou restitués ; l'impôt sur le revenu reste dû, mais la position nette est clairement meilleure qu'en cas de forclusion. Pour un couple marié avec un dépôt commun, l'effort de contrôle ne double guère – le montant du remboursement potentiel, si.</p>
<p>Faites le calcul avant de décider : revenu brut, impôt retenu, effet attendu de l'impôt sur le revenu, risque de rappel d'impôt. Les démarches d'une demande en ligne sont sobres ; les montants souvent moins.</p>
<p><strong>Conseil pratique :</strong> commencez par les dépôts que vous ne gérez plus vous-même – comptes d'enfants, anciens comptes d'épargne et de libre passage, polices d'assurance à rendement. Les prescriptions les plus fréquentes concernent des titres auxquels plus personne n'a pensé après le dernier changement de banque.</p>"""),
 ("En bref",
  """<ul><li>Art. 32 al. 1 LIA : le droit au remboursement des dividendes et intérêts 2023 s'éteint le 31 décembre 2026 – forclusion, en principe ni interrompue ni prolongeable.</li>
<li>Les contribuables taxés ordinairement déclarent le brut dans l'état des titres ; la déclaration vaut demande de restitution (art. 30 LIA).</li>
<li>Demande directe à l'AFC : portail ESTV ou formulaire électronique 25 ; dépôt possible dès l'année suivant la prestation due (art. 29 LIA), réception avant le 31.12.2026.</li>
<li>L'impôt à la source étranger suit un autre régime (DA-1) ; pour les fonds, la restitution passe par la direction du fonds.</li>
<li>Prochaines échéances : revenus 2024 jusqu'au 31.12.2027, revenus 2025 jusqu'au 31.12.2028.</li></ul>"""),
]

# ---------------- IT ----------------
it_title = "Imposta preventiva 2023: i rimborsi prescrivono il 31 dicembre 2026"
it_meta = "L'imposta preventiva del 35 % su dividendi e interessi del 2023 è definitivamente persa se entro il 31 dicembre 2026 non viene presentata nessuna domanda (art. 32 cpv. 1 LIP). Come verificare il Suo deposito e recuperare il Suo denaro."
it_secs = [
 ("Perché la scadenza è vicina: il termine di tre anni",
  """<p>In Svizzera ogni dividende e interesse di fonte svizzera è gravato alla fonte da un'imposta preventiva del 35 % (art. 13 della legge federale sull'imposta preventiva, LIP). La banca o la società trattiene il prelievo e lo versa all'Amministrazione federale delle contribuzioni (AFC). Il denaro è restituito solo su richiesta – e il diritto di presentarla si estingue: «Il diritto al rimborso si estingue se la domanda non è presentata entro tre anni dalla scadenza dell'anno civile nel corso del quale la prestazione imponibile è divenuta esigibile» (art. 32 cpv. 1 LIP).</p>
<p>Per i redditi 2023 il termine scade il 31 dicembre 2026. L'AFC sottolinea espressamente che si tratta di un termine di prescrizione in senso stretto (decadenza) che, di principio, non può essere né interrotto né prorogato. Dividendi e interessi 2023 mai dichiarati, per i quali entro fine anno non si fa nulla, sono perduti definitivamente.</p>
<p>I prossimi countdown seguono un ritmo annuale: redditi 2024 fino al 31 dicembre 2027, redditi 2025 fino al 31 dicembre 2028. Compresa la logica, la verifica diventa una routine di fine anno.</p>
<p><strong>Consiglio pratico:</strong> fissi il 31 dicembre nel Suo calendario come data fissa di controllo – ogni periodo d'imposta ha il proprio termine e nessuno è spostabile a posteriori.</p>"""),
 ("La via semplice: la dichiarazione nella tassazione",
  """<p>Chi è tassato secondo la procedura ordinaria ha di fatto già presentato la domanda: dichiarare i redditi nell'elenco dei titoli della dichiarazione d'imposte cantonale vale come domanda di rimborso presso il Cantone di domicilio (art. 30 LIP). L'autorità fiscale accredita d'ufficio l'imposta preventiva nella tassazione – a condizione che i redditi siano dichiarati integralmente, cioè lordi, imposta del 35 % inclusa.</p>
<p>Il caso critico classico sono i titoli assenti dalla dichiarazione: partecipazioni dimenticate, piccoli dividendi, conti che si ritenevano invisibili. Con lo scambio automatico di informazioni (SAI) con la maggior parte degli Stati partner queste lacune emergono regolarmente nelle tassazioni successive – e senza dichiarazione non c'è rimborso.</p>
<p>Separi i due piani: una dichiarazione 2023 regolarizzata nei termini può ancora recuperare l'imposta preventiva, ma innesca una tassazione di supplenza sul reddito finora non imposto. Per gli occultamenti passati, la prima autodenuncia è senza pena: chi denuncia per la prima volta un occultamento fiscale non rischia nessuna multa – restano dovuti solo l'imposta evasa e l'interesse moratorio (art. 175 cpv. 3 LIFD); per ogni autodenuncia successiva la multa è ridotta a un quinto dell'imposta evasa (art. 175 cpv. 4). In caso di dubbi sulla configurazione faccia esaminare la pratica prima di depositare.</p>
<p><strong>Consiglio pratico:</strong> si faccia mandare per il 2023 i certificati annuali e gli estratti dei dividendi di tutte le banche e piattaforme – anche i conti che utilizza raramente. L'elenco lordo delle prestazioni esigibili mostra subito se ogni titolo è finito nella Sua dichiarazione.</p>"""),
 ("Senza accredito automatico: la procedura di rimborso diretta",
  """<p>L'accredito automatico tramite tassazione non copre tutti i casi: chi non presenta una dichiarazione, nel frattempo ha cambiato domicilio o è deceduto, o ha percepito redditi mai apparsi in alcuna tassazione, presenta la domanda per scritto all'AFC – al più semplice tramite il portale ESTV o il modulo elettronico 25 «Domanda di restituzione dell'imposta preventiva» (i moduli cartacei non sono più disponibili; la domanda può essere presentata al più presto dopo la scadenza dell'anno civile della prestazione – art. 29 LIP). Alleghi i giustificativi della prestazione imponibile, ad esempio l'estratto titoli di fine anno.</p>
<p>La domanda deve essere presentata entro il 31 dicembre 2026. L'AFC non conferma la ricezione delle domande di rimborso; le domande presentate online sono consultabili in ogni momento nel portale per quanto riguarda lo stato. Il deposito elettronico con riferimento verificabile prima delle festività è la via più sicura.</p>
<p>Per le successioni: il termine continua a decorrere per i redditi di una persona deceduta. Chi amministra un asse ereditario verifichi i depositi per eventuali crediti di rimborso non reclamati degli ultimi tre anni, prima che si estinguano uno dopo l'altro.</p>
<p><strong>Consiglio pratico:</strong> conservi l'estratto del portale o una copia della domanda con la data di presentazione fino all'accredito del rimborso – in caso di contestazione conta solo la prova di una domanda presentata prima del 31 dicembre.</p>"""),
 ("Ciò che il termine non risana: i contenitori vicini",
  """<p>Non tutto ciò che somiglia al 35 % è imposta preventiva svizzera: essa colpisce solo prestazioni svizzere imponibili – dividendi, parti di utile, interessi e taluni vantaggi monetari di società a partecipazione ravvicinata. I titoli esteri non sostengono imposta preventiva federale; lì entrano in linea di conto l'imposta alla fonte estera e la sua imputazione tramite l'allegato DA-1 della dichiarazione – regime diverso, regole diverse.</p>
<p>Secondo punto: ogni rimborso presuppone che i redditi siano dichiarati e tassati. In una tassazione corretta l'imposta preventiva è restituita integralmente; occultare i redditi lascia semplicemente il denaro dov'è – con in più il rischio di una tassazione di supplenza.</p>
<p>Terzo punto, per gli investimenti collettivi la restituzione dell'imposta preventiva prelevata a livello di fondo avviene di regola tramite la direzione del fondo, non tramite il singolo detentore di quote nel patrimonio privato. E un deposito aperto solo nel 2024 non pone alcuna questione 2023 – verifichi tuttavia i Suoi vecchi conti, averi di risparmio e polizze a rendimento.</p>
<p><strong>Consiglio pratico:</strong> tenga distinti i contenitori: 35 % imposta preventiva CH (redditi 2023: domanda entro il 31.12.2026), imposta alla fonte estera (DA-1, nessun termine LIP), averi in fondi (via la direzione del fondo) – tre regimi, tre checklist.</p>"""),
 ("Verifica rapida: l'importo in gioco",
  """<p>Un deposito medio con CHF 20'000 di dividendi e interessi lordi nel 2023 ha sostenuto CHF 7'000 di imposta preventiva. Mai dichiarato e senza domanda presentata entro il 31 dicembre 2026, questi CHF 7'000 sono perduti – indipendentemente dall'imposta sul reddito comunque dovuta su questi proventi.</p>
<p>Viceversa: dichiarati nella tassazione 2023 (o in una tassazione regolarizzata prima del termine), i CHF 7'000 sono accreditati o restituiti; l'imposta sul reddito resta dovuta, ma la posizione netta è chiaramente migliore della decadenza. Per una coppia sposata con un deposito in comune lo sforzo di verifica quasi non raddoppia – l'importo potenziale del rimborso sì.</p>
<p>Faccia i conti prima di decidere: reddito lordo, imposta trattenuta, effetto atteso dell'imposta sul reddito, rischio di tassazione di supplenza. L'onere di una domanda online è sobrio; gli importi spesso meno.</p>
<p><strong>Consiglio pratico:</strong> cominci dai depositi che non gestisce più direttamente – conti per figli, vecchi conti di risparmio e di libero passaggio, polizze con rendimento. Le decadenze più frequenti riguardano titoli a cui nessuno ha più pensato dopo l'ultimo cambio di banca.</p>"""),
 ("In sintesi",
  """<ul><li>Art. 32 cpv. 1 LIP: il diritto al rimborso di dividendi e interessi 2023 si estingue il 31 dicembre 2026 – decadenza, di principio né interrotta né prorogabile.</li>
<li>I contribuenti tassati ordinariamente dichiarano il lordo nell'elenco dei titoli; la dichiarazione vale come domanda di rimborso (art. 30 LIP).</li>
<li>Domanda diretta all'AFC: portale ESTV o modulo elettronico 25; presentazione possibile dall'anno successivo alla prestazione esigibile (art. 29 LIP), ricezione entro il 31.12.2026.</li>
<li>L'imposta alla fonte estera segue un altro regime (DA-1); per i fondi la restituzione passa tramite la direzione del fondo.</li>
<li>Prossimi termini: redditi 2024 entro il 31.12.2027, redditi 2025 entro il 31.12.2028.</li></ul>"""),
]

build("de", SLUG, de_title, de_meta, de_secs)
build("en", SLUG, en_title, en_meta, en_secs)
build("fr", SLUG, fr_title, fr_meta, fr_secs)
build("it", SLUG, it_title, it_meta, it_secs)
print("done")
