#!/usr/bin/env python3
"""Publish 2026-10-09: phishing-steuerbescheid-agov-betrug (de/en/fr/it).
Pinned topic (pin-2026-10-12, slot week active). Facts verified against
estv.admin.ch/de/digitale-bedrohungen (retrieved 2026-10-09),
agov.admin.ch + estv.admin.ch MM 06.10.2025 (AGOV/ePortal switch)."""
import subprocess, sys, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TPL = os.path.join(BASE, "scripts", "article_template.py")
SLUG = "phishing-steuerbescheid-agov-betrug"

DE = dict(
    title="Gefälschte Steuer-Mails und AGOV-Phishing: So erkennen Sie Betrug im Namen der Steuerverwaltung",
    meta="Die ESTV warnt vor betrügerischen E-Mails in ihrem Namen: Offizielle Bundes-Mails enden auf @admin.ch. Woran Fake-Rückerstattungen, betrügerische Anrufe und Phishing rund um den AGOV-Umstieg zu erkennen sind.",
    sections=[
        ("Die ESTV warnt: Betrugsmails im Namen der Steuerverwaltung",
         "<p>Die Eidgenössische Steuerverwaltung (ESTV) veröffentlicht auf ihrer Seite «Digitale Bedrohungen» laufend Warnungen vor betrügerischen Nachrichten, die sich als E-Mails der ESTV ausgeben. Zuletzt identifiziert wurden Absender mit Endungen wie <strong>@federaltaxadministration.com</strong> und <strong>@ftaswiss.live</strong> sowie zuvor gemeldete Adressen wie <strong>@miumg.edu.gt</strong> und <strong>kundenportal@hilfe-kundendienst.ch</strong>. Diese Listen sind laut ESTV nicht abschliessend — weitere Fälscher-Adressen kommen laufend dazu.</p>"
         "<p>Der einfachste Schutz ist eine Regel, die die Bundesbehörden selbst ausgeben: <strong>Offizielle E-Mails der Schweizer Bundesbehörden werden immer von Adressen versendet, die auf @admin.ch (oder eine Subdomain davon) enden.</strong> Alles andere — .com, .live, .ch-Adressen fremder Firmen — ist kein Behördenversand. Die ESTV fordert in ihren Warnungen unmissverständlich auf: keinen Link anklicken, keine Anhänge öffnen, keine persönlichen, finanziellen oder steuerlichen Informationen weitergeben.</p>"
         "<p><strong>Praxistipp:</strong> Prüfen Sie bei jeder «Steuer»-Mail den Absender im Volltext, nicht nur den Anzeigenamen. Betrüger schreiben in die Absenderzeile «ESTV» oder «Kantonales Steueramt», während die technische Adresse auf eine fremde Domain zeigt. Im Zweifel löschen Sie die Mail und öffnen Sie das offizielle Portal direkt durch manuelle Eingabe — nie über einen Link in der Nachricht.</p>"),
        ("Der Klassiker: die angebliche Steuerrückerstattung",
         "<p>Die häufigste Masche ist die Lockmeldung mit einer Erstattung: Die ESTV beschreibt eine betrügerische Nachricht, die eine angebliche <strong>Steuerrückerstattung von CHF 287</strong> ankündigt und darauf zielt, Bankdaten auf einer gefälschten Regierungswebsite zu ergattern. Die Wirkung beruht auf Freude und Nachlässigkeit — CHF 287 klingt klein und glaubwürdig, ein Formular mit IBAN-Eingabe klingt nach dem üblichen Erstattungsprozess.</p>"
         "<p>Wichtig zu wissen: Eine echte Rückerstattung der Verrechnungssteuer oder eine Erstattung der kantonalen Veranlagung wird <strong>nie auf ein privates Postkonto «angewiesen» und nie per Formular in einer E-Mail abgewickelt.</strong> Erstattungen laufen über die Steuererklärung bzw. die Veranlagung und werden auf das der Behörde bekannte Konto ausbezahlt. Wer wirklich eine Erstattung erwartet, prüft den Status direkt im offiziellen ePortal bzw. beim kantonalen Steueramt — über die von Hand eingegebene amtliche Domain, nicht über einen Link.</p>"
         "<p><strong>Praxistipp:</strong> Merken Sie sich die Devise «Erstattung = kein Link, kein Formular, keine neue IBAN». Jede Nachricht, die unter Zeitdruck («innerhalb von 72 Stunden bestätigen») Bank- oder Login-Daten für eine gutgeschriebene Summe verlangt, ist Betrug. Eine amtliche Verfügung kennt keine Dringlichkeits-Countdown.</p>"),
        ("Betrügerische Anrufe und Vishing: Rückruf-Fallen erkennen",
         "<p>Neben E-Mail warnt die ESTV auch vor <strong>betrügerischen Anrufen in ihrem Namen</strong>, die einen Rückruf verlangen, sowie vor Vishing — computergenerierten Telefonanrufen, die Echtheit vortäuschen, um an Daten zu gelangen. Die Behörde ist hier klar: Solche Anrufe ignorieren und <strong>nicht zurückrufen</strong>.</p>"
         "<p>Zum Schutz gibt die ESTV konkret vor: keine sensiblen Daten am Telefon preisgeben — auch dann nicht, wenn der Anrufer bereits korrekte Personalien von Ihnen nennt (das dient nur dem Vertrauenstrick); Gespräch sofort beenden, wenn Druck, Drohungen oder das Angebot von Fernzugriff ins Spiel kommen; automatisierte Computer-Stimmen ignorieren, besonders zu ungewöhnlichen Zeiten; und bei echtem Zweifel die offizielle Telefonnummer selbst heraussuchen und zurückrufen — nie die vom Anrufer genannte.</p>"
         "<p><strong>Praxistipp:</strong> Kein Steueramt und keine ESTV verlangt telefonisch Ihre AHV-Nummer, IBAN oder Zugangsdaten, und kein Amt bietet an, sich per Fernwartung auf Ihren Rechner zu schalten. Fernzugriff in einem «Steuer»-Gespräch ist ausnahmslos Betrug — Legen Sie auf und melden Sie den Fall der Polizei.</p>"),
        ("AGOV-Umstieg: Warum gerade jetzt die Phishing-Welle rollt",
         "<p>Die ESTV stellt ihre ePortal-Dienste um: Seit Mai 2026 läuft die MWST-Abrechnung ausschliesslich über «MWST-Abrechnung pro», und <strong>ab dem 31. Oktober 2026 sind Registrierung und Anmeldung im ePortal nur noch über das Behörden-Login AGOV möglich</strong>; das bisherige CH-Login wird Ende 2027 vollständig deaktiviert (Medienmitteilung der ESTV vom 6. Oktober 2025). Jede MWST-pflichtige Firma muss also bis Ende Oktober handeln — genau diesen Handlungsbedarf nutzen Betrüger mit Fake-Portalen und «Ihr Login läuft ab»-Mails aus.</p>"
         "<p>Der seriöse Einstieg führt ausschliesslich über die offiziellen Domains: <strong>www.agov.admin.ch</strong> für das Behörden-Login und die ESTV-Dienste über <strong>www.estv.admin.ch</strong> bzw. das dort verlinkte ePortal. AGOV selbst arbeitet ohne klassische Passwörter mit Geräteloggins und app-Bestätigung — ein «AGOV-Passwort zurücksetzen»-Link in einer E-Mail ist daher bereits ein Widerspruch zum System. Technische Hilfe leistet der offizielle Servicedesk der ESTV unter +41 58 461 61 11; Hilfestellungen sind zudem unter help.eiam.swiss verfügbar.</p>"
         "<p><strong>Praxistipp:</strong> Registrieren Sie AGOV frühzeitig — nicht am Deadline-Tag. Wer den Umstieg hinter sich hat, auf den wirken «Bestätigen Sie Ihr Login bis …»-Mails wie Werbung statt Dringlichkeit. Speichern Sie die offiziellen URLs als Lesezeichen und melden Sie Phishing-Versuche dem Nationalen Zentrum für Cybersicherheit (NCSC), das auf der ESTV-Warnseite als weitere Anlaufstelle verlinkt ist.</p>"),
        ("Was Sie im Ernstfall tun — und was nicht",
         "<p>Haben Sie auf einen Link geklickt, aber keine Daten eingegeben: nichts weiter veranlassen, Nachricht an das NCSC-Meldeverfahren weiterleiten und löschen — die ESTV verweist auf genau dieses Vorgehen («Melden Sie die Nachricht gemäß den geltenden Verfahren und löschen Sie sie»). Haben Sie Bank- oder Zugangsdaten preisgegeben, ist Schnelligkeit entscheidend: Bank sofort sperren lassen, bei Passwörtern alle Konten mit gleicher Kombination ändern und den Vorfall bei der Polizei sowie beim NCSC melden.</p>"
         "<p>Auch für Firmen gilt: Ein kompromittiertes ePortal-Login ist kein IT-Problem allein, sondern berührt die MWST-Abrechnungs- und Unterzeichnungsberechtigung. Informieren Sie die ESTV via offiziellen Kontaktweg und lassen Sie die Berechtigungen im myESTV-Bereich neu setzen. Beachten Sie schliesslich: Weder ESTV noch kantonale Steuerämter verschicken Mahnungen oder Verfügungen als E-Mail-Anhang mit Zahlungsaufforderung — solche Dokumente kommen auf dem Postweg oder über das offizielle amtliche Zustellportal.</p>"
         "<p><strong>Praxistipp:</strong> Sichern Sie die amtliche Warnseite als Referenz: estv.admin.ch/de/digitale-bedrohungen listet die identifizierten Fälscher-Adressen und Maschen laufend aktualisiert. Leiten Sie die Seite an Mitarbeitende, Eltern und Vereinsvorstände weiter — die Gruppe der 55+ ist von den «Erstattungs»-Mails überproportional betroffen.</p>"),
    ],
)

EN = dict(
    title="Fake Tax Emails and AGOV Phishing: How to Spot Scams Impersonating the Tax Administration",
    meta="The Swiss FTA warns of fraudulent emails sent in its name: official federal emails always come from @admin.ch addresses. How to recognise fake refunds, scam calls and phishing around the mandatory AGOV login switch.",
    sections=[
        ("The FTA is warning: scam emails in the name of the tax administration",
         "<p>The Federal Tax Administration (FTA/ESTV) continuously publishes warnings on its “Digital threats” page about fraudulent messages posing as FTA emails. Most recently identified sender domains include <strong>@federaltaxadministration.com</strong> and <strong>@ftaswiss.live</strong>, following earlier alerts about addresses such as <strong>@miumg.edu.gt</strong> and <strong>kundenportal@hilfe-kundendienst.ch</strong>. The FTA states these lists are not exhaustive — new spoofed addresses keep appearing.</p>"
         "<p>The simplest protection is a rule the federal authorities themselves publish: <strong>official emails from Swiss public authorities are always sent from addresses ending in @admin.ch (or a subdomain of it).</strong> Anything else — .com, .live, or .ch addresses belonging to unrelated companies — is not a government message. The FTA's instruction is unambiguous: do not click links, do not open attachments, do not share personal, financial or tax information.</p>"
         "<p><strong>Practical tip:</strong> In every “tax” email, check the sender in full, not just the display name. Scammers type “FTA” or “Cantonal tax office” into the sender line while the technical address points to a foreign domain. When in doubt, delete the message and open the official portal by typing the address yourself — never via a link in the email.</p>"),
        ("The classic trap: the phantom tax refund",
         "<p>The most common scheme is bait with a refund: the FTA describes a fraudulent message announcing an alleged <strong>tax refund of CHF 287</strong>, designed to lure victims into entering bank details on a fake government website. The trick works through relief and carelessness — CHF 287 sounds small and plausible, and an IBAN form sounds like the standard refund process.</p>"
         "<p>Key fact: a genuine withholding-tax refund or a cantonal assessment refund is <strong>never “transferred” to a private post account and never processed via a form in an email.</strong> Refunds run through your tax return or assessment and are paid to the account already known to the authority. If you genuinely expect a refund, check the status directly in the official ePortal or with your cantonal tax office — using the manually typed official domain, not a link.</p>"
         "<p><strong>Practical tip:</strong> Remember “a refund needs no link, no form, no new IBAN”. Any message that demands bank or login details under time pressure (“confirm within 72 hours”) for money credited to you is fraud. Official decisions do not come with countdown timers.</p>"),
        ("Fraudulent calls and vishing: spotting the callback trap",
         "<p>Beyond email, the FTA warns about <strong>fraudulent phone calls made in its name requesting a callback</strong>, and about vishing — computer-generated calls designed to appear genuine in order to harvest data. The authority is explicit: ignore such calls and <strong>do not call back</strong>.</p>"
         "<p>Its concrete protection advice: never disclose sensitive data by phone — even if the caller already knows correct personal details (that is only a trust trick); end the call immediately if there is pressure, threats or an offer of remote access; ignore automated computer voices, especially at unusual hours; and if in doubt, look up the official phone number yourself and call that — never a number given by the caller.</p>"
         "<p><strong>Practical tip:</strong> No tax office or the FTA ever asks by phone for your AVS number, IBAN or credentials, and no authority offers to remote-control your computer. Remote access in a “tax” call is fraud without exception — hang up and report it to the police.</p>"),
        ("The AGOV switch: why phishing waves follow deadline changes",
         "<p>The FTA is restructuring its ePortal services: since May 2026, VAT returns can only be filed through “VAT return pro”, and <strong>from 31 October 2026 registration and login in the ePortal are mandatory via the AGOV government login</strong>; the previous CH-Login will be fully deactivated at the end of 2027 (FTA media release of 6 October 2025). Every VAT-liable company must therefore act before the end of October — exactly the urgency scammers exploit with fake portals and “your login expires” emails.</p>"
         "<p>The legitimate route runs only through the official domains: <strong>www.agov.admin.ch</strong> for the government login and FTA services via <strong>www.estv.admin.ch</strong> or the ePortal linked there. AGOV itself works without classic passwords, using device-based login and app confirmation — so an “reset your AGOV password” link in an email already contradicts the system. Technical help comes from the official FTA service desk at +41 58 461 61 11; guides are available at help.eiam.swiss.</p>"
         "<p><strong>Practical tip:</strong> Register AGOV early — not on the deadline day. Once the switch is done, “confirm your login by …” emails read as noise rather than urgency. Save the official URLs as bookmarks and report phishing attempts to the National Cyber Security Centre (NCSC), which the FTA warning page links as the further point of contact.</p>"),
        ("What to do if it happens — and what not to do",
         "<p>If you clicked a link but entered no data: take no other action, forward the message to the NCSC reporting channel and delete it — precisely the procedure the FTA prescribes (“report the message according to the applicable procedures and delete it”). If you did disclose bank or login data, speed matters: have your bank block accounts immediately, change every account sharing the password, and report the incident to the police and the NCSC.</p>"
         "<p>Companies are equally affected: a compromised ePortal login is not just an IT problem — it touches VAT filing and signing authority for the business. Notify the FTA via its official contact channel and have the permissions under myESTV reset. And remember: neither the FTA nor cantonal tax offices send reminders or assessments as email attachments with payment demands — official documents arrive by post or through the official delivery portal.</p>"
         "<p><strong>Practical tip:</strong> Keep the official warning page as a reference: estv.admin.ch/de/digitale-bedrohungen lists the identified spoofed addresses and schemes, updated continuously. Forward it to employees, parents and club treasurers — people over 55 are hit disproportionately by the “refund” emails.</p>"),
    ],
)

FR = dict(
    title="Faux e-mails fiscaux et phishing AGOV : reconnaître les arnaques au nom de l'administration fiscale",
    meta="L'AFC alerte sur les e-mails frauduleux envoyés en son nom : les e-mails officiels de la Confédération proviennent toujours d'adresses @admin.ch. Faux remboursements, appels frauduleux et hameçonnage liés à la transition AGOV : les réflexes qui protègent.",
    sections=[
        ("L'AFC alerte : des e-mails frauduleux au nom de l'administration fiscale",
         "<p>L'Administration fédérale des contributions (AFC) publie sur sa page « Menaces numériques » des avertissements continus contre des messages qui usurquent son identité. Les dernières adresses d'expéditeurs identifiées portent des terminaisons comme <strong>@federaltaxadministration.com</strong> et <strong>@ftaswiss.live</strong>, après des alertes précédentes concernant notamment <strong>@miumg.edu.gt</strong> et <strong>kundenportal@hilfe-kundendienst.ch</strong>. Ces listes ne sont pas exhaustives : de nouvelles adresses frauduleuses apparaissent régulièrement.</p>"
         "<p>La protection la plus simple tient en une règle édictée par les autorités fédérales elles-mêmes : <strong>les e-mails officiels des autorités suisses proviennent toujours d'adresses se terminant par @admin.ch (ou un sous-domaine de celui-ci).</strong> Toute autre adresse — .com, .live ou un .ch appartenant à une société tierce — n'est pas un envoi officiel. L'AFC est sans ambiguïté : ne cliquez sur aucun lien, n'ouvrez aucune pièce jointe, ne communiquez aucune information personnelle, financière ou fiscale.</p>"
         "<p><strong>Conseil pratique :</strong> pour chaque e-mail « fiscal », vérifiez l'expéditeur en toutes lettres, pas seulement le nom affiché. Les escrocs saisissent « AFC » ou « Service des contributions » dans la ligne d'expédition alors que l'adresse technique renvoie à un domaine étranger. En cas de doute, supprimez le message et ouvrez le portail officiel en tapant vous-même l'adresse — jamais via un lien.</p>"),
        ("L'arnaque classique : le faux remboursement d'impôt",
         "<p>Le mode opératoire le plus répandu appâte par un remboursement : l'AFC décrit un message frauduleux annonçant un prétendu <strong>remboursement d'impôt de CHF 287</strong>, conçu pour soutirer des données bancaires sur un faux site gouvernemental. L'astuce joue sur le soulagement et la négligence — CHF 287 paraît modeste et crédible, et un formulaire IBAN ressemble au processus habituel.</p>"
         "<p>Fait essentiel : un vrai remboursement de l'impôt anticipé ou d'une taxation cantonale n'est <strong>jamais « ordonné » sur un compte postal privé et ne se traite jamais via un formulaire dans un e-mail.</strong> Les remboursements passent par la déclaration ou la décision de taxation et sont versés sur le compte déjà connu de l'autorité. Si vous attendez réellement un remboursement, vérifiez le statut directement dans l'ePortal officiel ou auprès de votre service cantonal — en tapant le domaine officiel, pas via un lien.</p>"
         "<p><strong>Conseil pratique :</strong> retenez la devise « remboursement = ni lien, ni formulaire, ni nouvel IBAN ». Tout message qui exige des données bancaires ou d'accès sous pression (« confirmer dans les 72 heures ») pour une somme qui vous serait due est une arnaque. Une décision officielle n'a pas de compte à rebours.</p>"),
        ("Appels frauduleux et hameçonnage vocal : refuser le rappel",
         "<p>Au-delà des e-mails, l'AFC met en garde contre des <strong>appels téléphoniques frauduleux usurpant son nom et demandant un rappel</strong>, ainsi que contre le vishing — des appels générés par ordinateur simulant la véracité pour soutirer des données. La consigne est claire : ignorer ces appels et <strong>ne pas rappeler</strong>.</p>"
         "<p>Ses recommandations concrètes : ne jamais communiquer de données sensibles par téléphone, même si l'appelant énonce correctement des informations personnelles vous concernant (pure manœuvre de confiance) ; raccrocher immédiatement en cas de pression, de menaces ou d'offre de prise de contrôle à distance ; ignorer les voix automatisées, surtout à des heures inhabituelles ; et en cas de doute, composer vous-même le numéro officiel trouvé seul — jamais celui dicté par l'appelant.</p>"
         "<p><strong>Conseil pratique :</strong> aucun service des contributions ni l'AFC ne demande par téléphone votre numéro AVS, votre IBAN ou vos identifiants, et aucune autorité ne propose de prendre le contrôle de votre ordinateur. Une demande d'accès à distance lors d'un appel « fiscal » est une arnaque sans exception — raccrochez et déposez plainte.</p>"),
        ("Transition AGOV : pourquoi les vagues de phishing suivent les échéances",
         "<p>L'AFC restructure ses services ePortal : depuis mai 2026, les déclarations TVA ne passent plus que par « Décompte TVA pro », et <strong>dès le 31 octobre 2026, l'inscription et la connexion à l'ePortal sont obligatoires via AGOV, le login des autorités suisses</strong> ; le CH-Login sera entièrement désactivé fin 2027 (communiqué de l'AFC du 6 octobre 2025). Toute entreprise assujettie à la TVA doit donc agir avant fin octobre — c'est précisément cet agenda qu'exploitent les faux portails et les e-mails « votre accès expire ».</p>"
         "<p>La voie légitime passe uniquement par les domaines officiels : <strong>www.agov.admin.ch</strong> pour le login des autorités et les services de l'AFC via <strong>www.estv.admin.ch</strong> ou l'ePortal qui y est lié. AGOV fonctionne sans mot de passe classique, avec des identifiants d'appareil et une confirmation par application — un lien « réinitialiser votre mot de passe AGOV » dans un e-mail contredit donc déjà le système. L'assistance technique est assurée par le service desk officiel de l'AFC au +41 58 461 61 11 ; les aides à l'utilisation se trouvent sur help.eiam.swiss.</p>"
         "<p><strong>Conseil pratique :</strong> inscrivez-vous à AGOV tôt — pas le jour de l'échéance. Une fois la transition faite, les e-mails « confirmez votre accès avant le … » ne sont plus que du bruit. Enregistrez les URL officielles en favoris et signalez les tentatives de phishing au Centre national pour la cybersécurité (NCSC), que la page d'avertissement de l'AFC cite comme point de contact.</p>"),
        ("Que faire en cas de pépin — et ce qu'il ne faut pas faire",
         "<p>Si vous avez cliqué un lien sans saisir de données : ne rien faire d'autre, transmettre le message au canal de signalement du NCSC et le supprimer — c'est exactement la procédure que l'AFC prescrit (« signalez le message selon les procédures en vigueur et supprimez-le »). Si vous avez communiqué des données bancaires ou d'accès, la rapidité compte : faire bloquer vos comptes auprès de la banque sans attendre, modifier tous les comptes partageant le même mot de passe et annoncer le cas à la police ainsi qu'au NCSC.</p>"
         "<p>Les entreprises sont concernées au même titre : un identifiant ePortal compromis n'est pas qu'un problème informatique — il touche la déclaration et la signature TVA pour l'organisation. Informez l'AFC par son canal de contact officiel et faites réinitialiser les autorisations dans la partie myESTV. Enfin, rappelez-vous : ni l'AFC ni les services cantonaux n'envoient de rappels ou de décisions en pièce jointe avec injonction de paiement — les documents officiels arrivent par poste ou via le canal de notification officiel.</p>"
         "<p><strong>Conseil pratique :</strong> gardez la page d'avertissement officielle comme référence : estv.admin.ch signale en continu les adresses usurpées et les modes opératoires. Transmettez-la à vos collaborateurs, vos parents et aux trésoriers d'associations — les plus de 55 ans sont frappés de manière disproportionnée par les e-mails « remboursement ».</p>"),
    ],
)

IT = dict(
    title="Finte e-mail fiscali e phishing AGOV: come riconoscere le truffe a nome dell'amministrazione fiscale",
    meta="L'AFC avverte delle e-mail fraudolente inviate a suo nome: la posta ufficiale della Confederazione proviene sempre da indirizzi @admin.ch. Finti rimborsi, telefonate ingannevoli e phishing legati al passaggio ad AGOV: come difendersi.",
    sections=[
        ("L'AFC avverte: e-mail fraudolente a nome dell'amministrazione fiscale",
         "<p>L'Amministrazione federale delle contribuzioni (AFC) pubblica in modo continuativo, sulla pagina «Minacce informatiche», avvisi concernenti messaggi che si spacciano per comunicazioni dell'AFC. Le ultime identità di mittenti identificate terminano con <strong>@federaltaxadministration.com</strong> e <strong>@ftaswiss.live</strong>, dopo segnalazioni precedenti su indirizzi come <strong>@miumg.edu.gt</strong> e <strong>kundenportal@hilfe-kundendienst.ch</strong>. L'AFC precisa che l'elenco non è esaustivo: nuovi indirizzi fraudolenti compaiono di continuo.</p>"
         "<p>La protezione più semplice si basa su una regola emanata dalle stesse autorità federali: <strong>le e-mail ufficiali delle autorità svizzere provengono sempre da indirizzi che terminano con @admin.ch (o un sottodominio).</strong> Qualsiasi altra forma — .com, .live o un .ch di terzi — non è una comunicazione ufficiale. L'AFC è categorica: non cliccare link, non aprire allegati, non trasmettere dati personali, finanziari o fiscali.</p>"
         "<p><strong>Suggerimento pratico:</strong> in ogni e-mail «fiscale» verifichi il mittente per esteso, non solo il nome visualizzato. I truffatori scrivono «AFC» o «Ufficio delle contribuzioni» nella riga del mittente, mentre l'indirizzo tecnico rinvia a un dominio estraneo. In caso di dubbio, cancelli il messaggio e apra il portale ufficiale digitando l'indirizzo a mano — mai tramite un link.</p>"),
        ("Il classico: il finto rimborso fiscale",
         "<p>La tecnica più diffusa esca con un rimborso: l'AFC descrive un messaggio fraudolento che annuncia un presunto <strong>rimborso d'imposte di CHF 287</strong>, progettato per carpire dati bancari su un falso sito governativo. L'inganno gioca su sollievo e superficialità: CHF 287 sembra una cifra modesta e verosimile, e un modulo IBAN assomiglia alla procedura usuale.</p>"
         "<p>Punto essenziale: un vero rimborso dell'imposta anticipata o di una tassazione cantonale <strong>non viene mai «ordinato» su un conto postale privato e non si gestisce mai con un modulo in un'e-mail.</strong> I rimborsi passano dalla dichiarazione o dalla decisione di tassazione e sono versati sul conto già noto all'autorità. Se attende davvero un rimborso, verifichi lo stato direttamente nell'ePortal ufficiale o presso l'ufficio cantonale — digitando il dominio ufficiale, non seguendo un link.</p>"
         "<p><strong>Suggerimento pratico:</strong> memorizzi la regola «rimborso = niente link, niente moduli, niente nuovi IBAN». Qualsiasi messaggio pretenda dati bancari o di accesso con l'urgenza («confermi entro 72 ore») per una somma che le sarebbe dovuta è una truffa. Una decisione ufficiale non ha conti alla rovescia.</p>"),
        ("Telefonate fraudolente e vishing: non richiami",
         "<p>Oltre alle e-mail, l'AFC avverte circa <strong>telefonate fraudolente a suo nome che richiedono un richiamo</strong>, e sul vishing — chiamate generate al computer che simulano autenticità per carpire dati. L'indicazione è netta: ignorare queste chiamate e <strong>non richiamare</strong>.</p>"
         "<p>Le misure concrete indicate: non comunicare dati sensibili al telefono, nemmeno se chi chiama enuncia correttamente Sue informazioni personali (è solo un trucco di fiducia); interrompere subito la conversazione in caso di pressione, minacce o offerta di accesso remoto; ignorare le voci automatizzate, specie a orari insoliti; e in caso di dubbio, comporre il numero ufficiale trovato autonomamente — mai quello dettato dall'interlocutore.</p>"
         "<p><strong>Suggerimento pratico:</strong> nessun ufficio delle contribuzioni né l'AFC chiede per telefono il numero AVS, l'IBAN o le credenziali, e nessuna autorità propone di controllare il Suo computer da remoto. Una richiesta di accesso remoto in una telefonata «fiscale» è una truffa senza eccezioni: riattacchi e annunci il caso alla polizia.</p>"),
        ("Passaggio ad AGOV: perché le ondate di phishing inseguono le scadenze",
         "<p>L'AFC riorganizza i servizi ePortal: da maggio 2026 il conteggio IVA avviene esclusivamente tramite «Conteggio IVA pro», e <strong>dal 31 ottobre 2026 registrazione e accesso all'ePortal sono obbligatori con AGOV, il login delle autorità svizzere</strong>; il CH-Login sarà disattivato definitivamente a fine 2027 (comunicato AFC del 6 ottobre 2025). Ogni impresa IVA soggetta all'obbligo deve quindi agire prima di fine ottobre: è precisamente questa urgenza che i falsi portali e le e-mail «il Suo accesso scade» sfruttano.</p>"
         "<p>La via legittima passa soltanto per i domini ufficiali: <strong>www.agov.admin.ch</strong> per il login delle autorità e i servizi AFC tramite <strong>www.estv.admin.ch</strong> o l'ePortal ivi collegato. AGOV funziona senza password classiche, con dispositivi e conferma tramite app — un link «reimposti la password AGOV» in un'e-mail contraddice già il sistema. L'assistenza tecnica è fornita dal service desk ufficiale AFC al +41 58 461 61 11; le guide sono disponibili su help.eiam.swiss.</p>"
         "<p><strong>Suggerimento pratico:</strong> si registri ad AGOV per tempo, non il giorno della scadenza. A transizione compiuta, le e-mail «confermi l'accesso entro il …» diventano rumore, non urgenza. Salvi i URL ufficiali tra i preferiti e segnali i tentativi di phishing al Centro nazionale per la cibersicurezza (NCSC), indicato nella pagina di avviso dell'AFC come punto di riferimento.</p>"),
        ("Cosa fare se succede — e cosa non fare",
         "<p>Se ha cliccato un link senza inserire dati: non faccia altro, trasmetta il messaggio al canale di segnalazione dell'NCSC e lo cancelli — è esattamente la procedura prescritta dall'AFC («segnali il messaggio secondo le procedure vigenti e lo cancelli»). Se invece ha comunicato dati bancari o di accesso, la rapidità è decisiva: faccia bloccare i conti presso la banca senza indugio, cambi tutti gli accessi che condividono la stessa password e annunci il caso alla polizia e all'NCSC.</p>"
         "<p>Anche per le imprese vale lo stesso: un accesso ePortal compromesso non è soltanto un problema informatico — tocca la presentazione e la firma dei conteggi IVA. Informi l'AFC tramite il canale di contatto ufficiale e faccia reimpostare le autorizzazioni nell'area myESTV. E ricordi: né l'AFC né gli uffici cantonali inviano solleciti o decisioni come allegati con ingiunzioni di pagamento — i documenti ufficiali giungono per posta o tramite il canale di notifica ufficiale.</p>"
         "<p><strong>Suggerimento pratico:</strong> conservi la pagina di avviso ufficiale come riferimento: estv.admin.ch elenca in continuo aggiornamento gli indirizzi fraudolenti identificati e le modalità usate. La trasmetta ai collaboratori, ai genitori e ai cassieri delle associazioni — gli over 55 sono colpiti in modo sproporzionato dalle e-mail di finto rimborso.</p>"),
    ],
)

def run(lang, art):
    args = [sys.executable, TPL, lang, SLUG, art["title"], art["meta"]]
    for h2, body in art["sections"]:
        args += [h2, body]
    r = subprocess.run(args, capture_output=True, text=True)
    print(f"[{lang}] rc={r.returncode} {r.stdout.strip()} {r.stderr.strip()[:300]}")
    return r.returncode == 0

ok = all(run(*x) for x in [("de", DE), ("en", EN), ("fr", FR), ("it", IT)])
sys.exit(0 if ok else 1)
